/**
 * Mobility Rider App API
 * Generated by HOJAI Studio
 *
 * Features:
 * - Ride booking (Auto, Moto, Sedan, SUV)
 * - Real-time driver tracking
 * - Surge pricing
 * - Payment processing
 * - Ride history
 */
import express from 'express';
import cors from 'cors';
import { v4 as uuidv4 } from 'uuid';

const app = express();

// ── Internal Auth ────────────────────────────────────────────────
function requireInternal(req, res, next) {
  const token = req.headers['x-internal-token'];
  const expected = process.env.INTERNAL_SERVICE_TOKEN;
  if (token && expected && token === expected) {
    req.user = { type: 'service', id: 'internal' };
    return next();
  }
  return res.status(401).json({ error: 'Unauthorized' });
}

app.use(cors(), express.json());
const PORT = process.env.PORT || 3000;

// ── Sample Data ───────────────────────────────────────────────────────────────

const drivers = [
  { id: 'd1', name: 'Rajesh K', vehicle: 'Maruti Swift', type: 'sedan', rating: 4.8, plate: 'DL 01 AB 1234', lat: 28.6139, lng: 77.2090 },
  { id: 'd2', name: 'Amit S', vehicle: 'Hyundai i20', type: 'hatchback', rating: 4.6, plate: 'DL 02 CD 5678', lat: 28.6145, lng: 77.2100 },
  { id: 'd3', name: 'Priya M', vehicle: 'Toyota Innova', type: 'suv', rating: 4.9, plate: 'DL 03 EF 9012', lat: 28.6150, lng: 77.2080 },
  { id: 'd4', name: 'Vikram R', vehicle: 'Honda Activa', type: 'auto', rating: 4.5, plate: 'DL 04 GH 3456', lat: 28.6140, lng: 77.2110 },
];

const rides = new Map();
const userRides = new Map();

// ── Fare Calculation ────────────────────────────────────────────────────────

const VEHICLE_TYPES = {
  auto: { name: 'Auto', multiplier: 1.0, capacity: 3, baseFare: 25, perKm: 8, perMin: 1 },
  moto: { name: 'Moto', multiplier: 0.7, capacity: 2, baseFare: 15, perKm: 6, perMin: 0.5 },
  sedan: { name: 'Sedan', multiplier: 1.5, capacity: 4, baseFare: 40, perKm: 12, perMin: 1.5 },
  suv: { name: 'SUV', multiplier: 2.0, capacity: 6, baseFare: 60, perKm: 18, perMin: 2 }
};

function calculateFare(vehicleType, distanceKm, durationMin, surgeMultiplier = 1) {
  const type = VEHICLE_TYPES[vehicleType] || VEHICLE_TYPES.sedan;
  const base = type.baseFare + (type.perKm * distanceKm) + (type.perMin * durationMin);
  return Math.round(base * surgeMultiplier);
}

// ── Routes ─────────────────────────────────────────────────────────────────────

app.get('/health', (_, res) => res.json({ status: 'ok', app: 'mobility-rider' }));

// Get vehicle types
app.get('/api/vehicle-types', (_, res) => {
  const types = Object.entries(VEHICLE_TYPES).map(([id, v]) => ({
    id,
    name: v.name,
    capacity: v.capacity,
    baseFare: v.baseFare,
    perKm: v.perKm
  }));
  res.json({ success: true, types });
});

// Get fare estimate
app.get('/api/fare-estimate', (req, res) => {
  const { vehicleType, pickupLat, pickupLng, dropLat, dropLng } = req.query;

  // Mock distance and duration
  const distanceKm = Math.random() * 15 + 2; // 2-17 km
  const durationMin = Math.round(distanceKm * 3); // ~3 min per km

  // Check for surge (mock)
  const hour = new Date().getHours();
  const isPeakHour = hour >= 9 && hour <= 11 || hour >= 18 && hour <= 21;
  const surgeMultiplier = isPeakHour ? 1.5 + Math.random() * 0.5 : 1.0;

  const estimates = Object.entries(VEHICLE_TYPES).map(([id, v]) => ({
    vehicleType: id,
    name: v.name,
    distance: Math.round(distanceKm * 10) / 10,
    duration: durationMin,
    fare: calculateFare(id, distanceKm, durationMin, 1),
    surgeFare: calculateFare(id, distanceKm, durationMin, surgeMultiplier),
    surge: surgeMultiplier > 1 ? `${surgeMultiplier.toFixed(1)}x` : null
  }));

  res.json({
    success: true,
    estimates,
    surge: surgeMultiplier > 1,
    surgeMultiplier
  });
});

// Book ride
app.post('/api/rides', requireInternal, (req, res) => {
  const { userId, vehicleType, pickup, drop, scheduledTime } = req.body;

  if (!userId || !vehicleType) {
    return res.status(400).json({ error: 'userId and vehicleType required' });
  }

  // Mock distance calculation
  const distanceKm = Math.random() * 15 + 2;
  const durationMin = Math.round(distanceKm * 3);
  const surgeMultiplier = 1.0;
  const fare = calculateFare(vehicleType, distanceKm, durationMin, surgeMultiplier);

  // Find nearby drivers (mock)
  const availableDrivers = drivers.filter(d => d.type === vehicleType || vehicleType === 'sedan');

  const ride = {
    id: `RD${Date.now()}`,
    userId,
    vehicleType,
    pickup,
    drop,
    status: 'searching',
    distance: Math.round(distanceKm * 10) / 10,
    duration: durationMin,
    fare,
    surgeMultiplier,
    drivers: availableDrivers.slice(0, 3),
    driverId: null,
    otp: Math.floor(1000 + Math.random() * 9000),
    createdAt: new Date().toISOString()
  };

  rides.set(ride.id, ride);

  // Track user rides
  if (!userRides.has(userId)) userRides.set(userId, []);
  userRides.get(userId).push(ride.id);

  res.status(201).json({ success: true, ride });
});

// Accept by driver
app.post('/api/rides/:id/accept', requireInternal, (req, res) => {
  const { driverId } = req.body;
  const ride = rides.get(req.params.id);

  if (!ride) return res.status(404).json({ error: 'Ride not found' });

  const driver = drivers.find(d => d.id === driverId);
  if (!driver) return res.status(404).json({ error: 'Driver not found' });

  ride.driverId = driverId;
  ride.driver = driver;
  ride.status = 'accepted';
  ride.acceptedAt = new Date().toISOString();

  rides.set(ride.id, ride);

  res.json({ success: true, ride });
});

// Start ride
app.post('/api/rides/:id/start', requireInternal, (req, res) => {
  const ride = rides.get(req.params.id);
  if (!ride) return res.status(404).json({ error: 'Ride not found' });

  ride.status = 'in_progress';
  ride.startedAt = new Date().toISOString();
  rides.set(ride.id, ride);

  res.json({ success: true, ride });
});

// Complete ride
app.post('/api/rides/:id/complete', requireInternal, (req, res) => {
  const ride = rides.get(req.params.id);
  if (!ride) return res.status(404).json({ error: 'Ride not found' });

  ride.status = 'completed';
  ride.completedAt = new Date().toISOString();
  rides.set(ride.id, ride);

  res.json({ success: true, ride });
});

// Cancel ride
app.post('/api/rides/:id/cancel', requireInternal, (req, res) => {
  const { reason } = req.body;
  const ride = rides.get(req.params.id);
  if (!ride) return res.status(404).json({ error: 'Ride not found' });

  ride.status = 'cancelled';
  ride.cancelReason = reason;
  ride.cancelledAt = new Date().toISOString();
  rides.set(ride.id, ride);

  res.json({ success: true, ride });
});

// Get ride status
app.get('/api/rides/:id', (req, res) => {
  const ride = rides.get(req.params.id);
  if (!ride) return res.status(404).json({ error: 'Ride not found' });
  res.json({ success: true, ride });
});

// Get user's rides
app.get('/api/rides/user/:userId', (req, res) => {
  const userRideIds = userRides.get(req.params.userId) || [];
  const userRidesList = userRideIds.map(id => rides.get(id)).filter(Boolean);
  res.json({ success: true, rides: userRidesList });
});

// Track driver location
app.get('/api/rides/:id/track', (req, res) => {
  const ride = rides.get(req.params.id);
  if (!ride) return res.status(404).json({ error: 'Ride not found' });

  // Mock tracking
  const progress = ride.status === 'in_progress' ? 0.5 : ride.status === 'accepted' ? 0.1 : 0;
  const driverLat = ride.pickup?.lat + (ride.drop?.lat - ride.pickup?.lat) * progress;
  const driverLng = ride.pickup?.lng + (ride.drop?.lng - ride.pickup?.lng) * progress;

  res.json({
    success: true,
    tracking: {
      rideId: ride.id,
      status: ride.status,
      driver: ride.driver,
      eta: ride.status === 'in_progress' ? `${Math.round(ride.duration * (1 - progress))} mins` : `${ride.duration} mins`,
      driverLocation: ride.driver ? { lat: driverLat, lng: driverLng } : null
    }
  });
});

// Payment
app.post('/api/rides/:id/pay', requireInternal, (req, res) => {
  const { method, promoCode } = req.body;
  const ride = rides.get(req.params.id);
  if (!ride) return res.status(404).json({ error: 'Ride not found' });

  let finalFare = ride.fare;
  let discount = 0;

  // Apply promo
  if (promoCode === 'FIRST10') {
    discount = Math.round(finalFare * 0.1);
    finalFare -= discount;
  }

  ride.payment = {
    method,
    baseFare: ride.fare,
    discount,
    finalFare,
    status: 'pending',
    transactionId: `TXN${Date.now()}`
  };

  rides.set(ride.id, ride);
  res.json({ success: true, payment: ride.payment });
});

// Verify payment
app.post('/api/rides/:id/payment/verify', requireInternal, (req, res) => {
  const ride = rides.get(req.params.id);
  if (!ride) return res.status(404).json({ error: 'Ride not found' });

  ride.payment.status = 'completed';
  rides.set(ride.id, ride);

  res.json({ success: true, payment: ride.payment });
});

// Emergency
app.post('/api/rides/:id/emergency', requireInternal, (req, res) => {
  const ride = rides.get(req.params.id);
  if (!ride) return res.status(404).json({ error: 'Ride not found' });

  res.json({
    success: true,
    message: 'Emergency services have been notified. Stay calm.',
    emergency: {
      rideId: ride.id,
      driver: ride.driver,
      location: ride.pickup,
      reportedAt: new Date().toISOString()
    }
  });
});

// Rating
app.post('/api/rides/:id/rate', requireInternal, (req, res) => {
  const { rating, comment } = req.body;
  const ride = rides.get(req.params.id);
  if (!ride) return res.status(404).json({ error: 'Ride not found' });

  ride.rating = { rating, comment, ratedAt: new Date().toISOString() };
  rides.set(ride.id, ride);

  res.json({ success: true, message: 'Thank you for your feedback!' });
});

// Support
app.post('/api/support', requireInternal, (req, res) => {
  const { rideId, issue, description } = req.body;

  const ticket = {
    id: `TKT${Date.now()}`,
    rideId,
    issue,
    description,
    status: 'open',
    createdAt: new Date().toISOString()
  };

  res.status(201).json({ success: true, ticket });
});

app.listen(PORT, () => {
  console.log(`
╔══════════════════════════════════════════════════════════════╗
║  🚗  Mobility Rider App — PORT ${PORT}                       ║
║  AI-powered like Uber/Ola                           ║
╠══════════════════════════════════════════════════════════════╣
║  Vehicles: ${Object.keys(VEHICLE_TYPES).length} types                                 ║
║  Drivers: ${drivers.length} nearby                                   ║
╚══════════════════════════════════════════════════════════════╝
  `);
});

export default app;
