/**
 * Food Delivery Customer App API
 * Generated by HOJAI Studio
 *
 * Features:
 * - Restaurant discovery
 * - Menu browsing
 * - Cart & ordering
 * - Real-time tracking
 * - Reviews & ratings
 */
import express from 'express';
import cors from 'cors';
import { v4 as uuidv4 } from 'uuid';

const app = express();

// ── Internal Auth ────────────────────────────────────────────────
function requireInternal(req, res, next) {
  const token = req.headers['x-internal-token'];
  const expected = process.env.INTERNAL_SERVICE_TOKEN;
  if (token && expected && token === expected) {
    req.user = { type: 'service', id: 'internal' };
    return next();
  }
  return res.status(401).json({ error: 'Unauthorized' });
}

app.use(cors(), express.json());
const PORT = process.env.PORT || 3000;

// ── Sample Data ───────────────────────────────────────────────────────────────

const restaurants = [
  { id: 'r1', name: 'The Biryani House', cuisine: 'Biryani', rating: 4.5, deliveryTime: '25-30', deliveryFee: 40, minOrder: 200, image: 'https://picsum.photos/400/300?10', featured: true, categories: ['biryani', 'north-indian'] },
  { id: 'r2', name: 'Pizza Palace', cuisine: 'Pizza', rating: 4.3, deliveryTime: '30-35', deliveryFee: 50, minOrder: 300, image: 'https://picsum.photos/400/300?11', featured: true, categories: ['pizza', 'italian'] },
  { id: 'r3', name: 'Burger Junction', cuisine: 'Burgers', rating: 4.6, deliveryTime: '20-25', deliveryFee: 30, minOrder: 150, image: 'https://picsum.photos/400/300?12', featured: false, categories: ['burgers', 'fast-food'] },
  { id: 'r4', name: 'Sushi Master', cuisine: 'Japanese', rating: 4.8, deliveryTime: '35-40', deliveryFee: 60, minOrder: 500, image: 'https://picsum.photos/400/300?13', featured: true, categories: ['sushi', 'japanese'] },
  { id: 'r5', name: 'Tandoori Nights', cuisine: 'North Indian', rating: 4.4, deliveryTime: '25-30', deliveryFee: 35, minOrder: 250, image: 'https://picsum.photos/400/300?14', featured: false, categories: ['tandoori', 'north-indian'] },
  { id: 'r6', name: 'Thai Delight', cuisine: 'Thai', rating: 4.5, deliveryTime: '30-35', deliveryFee: 45, minOrder: 300, image: 'https://picsum.photos/400/300?15', featured: false, categories: ['thai', 'asian'] },
  { id: 'r7', name: 'Ice Cream Paradise', cuisine: 'Desserts', rating: 4.7, deliveryTime: '20-25', deliveryFee: 25, minOrder: 100, image: 'https://picsum.photos/400/300?16', featured: false, categories: ['ice-cream', 'desserts'] },
  { id: 'r8', name: 'Healthy Bowl', cuisine: 'Healthy', rating: 4.4, deliveryTime: '25-30', deliveryFee: 40, minOrder: 200, image: 'https://picsum.photos/400/300?17', featured: true, categories: ['healthy', 'salads'] }
];

const menuItems = {
  'r1': [
    { id: 'm1', name: 'Chicken Biryani', price: 299, description: 'Aromatic basmati rice with tender chicken', image: 'https://picsum.photos/200/200?20', category: 'biryani', popular: true },
    { id: 'm2', name: 'Mutton Biryani', price: 399, description: 'Premium mutton with special spices', image: 'https://picsum.photos/200/200?21', category: 'biryani', popular: true },
    { id: 'm3', name: 'Paneer Tikka', price: 199, description: 'Grilled paneer with mint chutney', image: 'https://picsum.photos/200/200?22', category: 'starters', popular: false },
    { id: 'm4', name: 'Dal Makhani', price: 149, description: 'Creamy black lentils', image: 'https://picsum.photos/200/200?23', category: 'curry', popular: false }
  ],
  'r2': [
    { id: 'm5', name: 'Margherita Pizza', price: 299, description: 'Classic tomato and mozzarella', image: 'https://picsum.photos/200/200?24', category: 'pizza', popular: true },
    { id: 'm6', name: 'Pepperoni Pizza', price: 399, description: 'Spicy pepperoni with cheese', image: 'https://picsum.photos/200/200?25', category: 'pizza', popular: true },
    { id: 'm7', name: 'Garlic Bread', price: 99, description: 'Crispy garlic breadsticks', image: 'https://picsum.photos/200/200?26', category: 'sides', popular: false }
  ]
};

const orders = new Map();
const carts = new Map();

// ── Routes ─────────────────────────────────────────────────────────────────────

app.get('/health', (_, res) => res.json({ status: 'ok', app: 'food-delivery-customer' }));

// Restaurants
app.get('/api/restaurants', (req, res) => {
  const { cuisine, search, featured, limit = 20 } = req.query;
  let results = [...restaurants];

  if (cuisine) results = results.filter(r => r.cuisine.toLowerCase().includes(cuisine.toLowerCase()));
  if (search) results = results.filter(r => r.name.toLowerCase().includes(search.toLowerCase()) || r.cuisine.toLowerCase().includes(search.toLowerCase()));
  if (featured === 'true') results = results.filter(r => r.featured);

  res.json({ success: true, restaurants: results.slice(0, parseInt(limit)), count: results.length });
});

app.get('/api/restaurants/:id', (req, res) => {
  const restaurant = restaurants.find(r => r.id === req.params.id);
  if (!restaurant) return res.status(404).json({ error: 'Restaurant not found' });

  const items = menuItems[req.params.id] || [];
  res.json({ success: true, restaurant: { ...restaurant, menu: items } });
});

app.get('/api/cuisines', (_, res) => {
  const cuisines = [...new Set(restaurants.map(r => r.cuisine))];
  res.json({ success: true, cuisines });
});

// Menu
app.get('/api/restaurants/:id/menu', (req, res) => {
  const items = menuItems[req.params.id] || [];
  const { category } = req.query;

  let filtered = items;
  if (category) filtered = items.filter(i => i.category === category);

  res.json({ success: true, menu: filtered });
});

// Cart
app.post('/api/cart/add', requireInternal, (req, res) => {
  const { userId, restaurantId, itemId, quantity = 1, notes } = req.body;

  if (!userId || !restaurantId || !itemId) {
    return res.status(400).json({ error: 'userId, restaurantId, and itemId required' });
  }

  const cartKey = `${userId}_${restaurantId}`;
  if (!carts.has(cartKey)) {
    carts.set(cartKey, { restaurantId, items: [], subtotal: 0 });
  }

  const cart = carts.get(cartKey);
  const restaurant = restaurants.find(r => r.id === restaurantId);
  const menu = menuItems[restaurantId] || [];
  const item = menu.find(m => m.id === itemId);

  if (!item) return res.status(404).json({ error: 'Item not found' });

  const existing = cart.items.find(i => i.itemId === itemId);
  if (existing) {
    existing.quantity += quantity;
  } else {
    cart.items.push({ itemId, name: item.name, price: item.price, quantity, notes });
  }

  cart.subtotal = cart.items.reduce((sum, i) => sum + i.price * i.quantity, 0);
  cart.deliveryFee = restaurant.deliveryFee;

  res.json({ success: true, cart });
});

app.get('/api/cart/:userId/:restaurantId', (req, res) => {
  const cartKey = `${req.params.userId}_${req.params.restaurantId}`;
  const cart = carts.get(cartKey);

  if (!cart) {
    return res.json({ success: true, cart: { items: [], subtotal: 0, deliveryFee: 0, total: 0 } });
  }

  const restaurant = restaurants.find(r => r.id === req.params.restaurantId);
  res.json({
    success: true,
    cart: {
      ...cart,
      restaurantName: restaurant?.name,
      total: cart.subtotal + cart.deliveryFee
    }
  });
});

app.delete('/api/cart/:userId/:restaurantId', requireInternal, (req, res) => {
  const cartKey = `${req.params.userId}_${req.params.restaurantId}`;
  carts.delete(cartKey);
  res.json({ success: true });
});

// Orders
app.post('/api/orders', requireInternal, (req, res) => {
  const { userId, restaurantId, address, paymentMethod } = req.body;

  const cartKey = `${userId}_${restaurantId}`;
  const cart = carts.get(cartKey);

  if (!cart || cart.items.length === 0) {
    return res.status(400).json({ error: 'Cart is empty' });
  }

  const restaurant = restaurants.find(r => r.id === restaurantId);

  const order = {
    id: `ORD${Date.now()}`,
    userId,
    restaurantId,
    restaurantName: restaurant.name,
    items: [...cart.items],
    subtotal: cart.subtotal,
    deliveryFee: cart.deliveryFee,
    total: cart.subtotal + cart.deliveryFee,
    address,
    paymentMethod,
    status: 'confirmed',
    driver: null,
    eta: restaurant.deliveryTime,
    createdAt: new Date().toISOString()
  };

  orders.set(order.id, order);
  carts.delete(cartKey);

  res.status(201).json({ success: true, order });
});

app.get('/api/orders/:userId', (req, res) => {
  const userOrders = Array.from(orders.values())
    .filter(o => o.userId === req.params.userId)
    .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));

  res.json({ success: true, orders: userOrders });
});

app.get('/api/orders/:userId/:orderId', (req, res) => {
  const order = orders.get(req.params.orderId);
  if (!order || order.userId !== req.params.userId) {
    return res.status(404).json({ error: 'Order not found' });
  }
  res.json({ success: true, order });
});

// Track Order
app.get('/api/track/:orderId', (req, res) => {
  const order = orders.get(req.params.orderId);
  if (!order) return res.status(404).json({ error: 'Order not found' });

  // Simulate tracking updates
  const trackingSteps = [
    { status: 'confirmed', message: 'Order confirmed', time: order.createdAt },
    { status: 'preparing', message: 'Restaurant is preparing your food', time: new Date(Date.now() + 5 * 60000).toISOString() },
    { status: 'picked_up', message: 'Driver picked up your order', time: new Date(Date.now() + 15 * 60000).toISOString() },
    { status: 'on_the_way', message: 'Your order is on the way', time: new Date(Date.now() + 20 * 60000).toISOString() },
    { status: 'delivered', message: 'Order delivered', time: new Date(Date.now() + 30 * 60000).toISOString() }
  ];

  res.json({
    success: true,
    tracking: {
      orderId: order.id,
      status: order.status,
      eta: order.eta,
      driver: order.driver,
      steps: trackingSteps
    }
  });
});

// Reviews
app.post('/api/reviews', requireInternal, (req, res) => {
  const { orderId, rating, comment } = req.body;
  const order = orders.get(orderId);

  if (!order) return res.status(404).json({ error: 'Order not found' });

  const review = {
    id: uuidv4(),
    orderId,
    restaurantId: order.restaurantId,
    rating,
    comment,
    createdAt: new Date().toISOString()
  };

  res.status(201).json({ success: true, review });
});

// Offers
app.get('/api/offers', (_, res) => {
  res.json({
    success: true,
    offers: [
      { id: 'o1', code: 'FIRST50', discount: 50, minOrder: 200, type: 'flat' },
      { id: 'o2', code: 'SAVE20', discount: 20, minOrder: 300, type: 'percent', max: 100 },
      { id: 'o3', code: 'FREEDELIVERY', discount: 0, minOrder: 500, type: 'free_delivery' }
    ]
  });
});

app.post('/api/offers/validate', requireInternal, (req, res) => {
  const { code, orderTotal } = req.body;
  const offer = { id: 'o1', code: 'FIRST50', discount: 50, minOrder: 200, type: 'flat' };

  if (orderTotal < offer.minOrder) {
    return res.json({ success: false, error: `Minimum order ${offer.minOrder} required` });
  }

  res.json({ success: true, offer, discount: offer.discount });
});

app.listen(PORT, () => {
  console.log(`
╔══════════════════════════════════════════════════════════════╗
║  🍔  Food Delivery Customer App — PORT ${PORT}                  ║
║  AI-powered like Swiggy/Zomato                        ║
╠══════════════════════════════════════════════════════════════╣
║  Restaurants: ${restaurants.length}                                     ║
║  Menu Items: ${Object.values(menuItems).flat().length}                                         ║
╚══════════════════════════════════════════════════════════════╝
  `);
});

export default app;
