/**
 * OTA Passenger App - Generated by HOJAI Studio
 * Template: Online Travel Agency (OTA)
 *
 * Features:
 * - Hotel booking with PMS integration
 * - Flight search with GDS
 * - Holiday packages
 * - Corporate bookings
 * - AI trip planning
 */
import express from 'express';
import cors from 'cors';

const app = express();
app.use(cors(), express.json());
const PORT = process.env.PORT || 3000;

// Sample data
const hotels = [
  { id: 'h1', name: 'Taj Palace', city: 'Mumbai', price: 8500, rating: 4.8, amenities: ['pool', 'spa', 'wifi'] },
  { id: 'h2', name: 'Marriott Suites', city: 'Delhi', price: 7200, rating: 4.6, amenities: ['gym', 'wifi', 'restaurant'] },
  { id: 'h3', name: 'ITC Grand', city: 'Bangalore', price: 9500, rating: 4.9, amenities: ['pool', 'spa', 'parking', 'wifi'] },
];

const flights = [
  { id: 'f1', airline: 'Air India', from: 'Mumbai', to: 'Delhi', depart: '10:00', arrive: '12:30', price: 4500, class: 'economy' },
  { id: 'f2', airline: 'Indigo', from: 'Mumbai', to: 'Delhi', depart: '14:00', arrive: '16:15', price: 3800, class: 'economy' },
  { id: 'f3', airline: 'Vistara', from: 'Mumbai', to: 'Delhi', depart: '18:00', arrive: '20:30', price: 5200, class: 'business' },
];

const packages = [
  { id: 'p1', name: 'Goa Beach Holiday', nights: 3, hotels: 2, price: 25000, includes: ['hotel', 'flights', 'transfers'] },
  { id: 'p2', name: 'Kerala Backwaters', nights: 4, hotels: 3, price: 35000, includes: ['hotel', 'houseboat', 'meals', 'sightseeing'] },
  { id: 'p3', name: 'Rajasthan Heritage', nights: 5, hotels: 4, price: 45000, includes: ['hotel', 'flights', 'meals', 'tours'] },
];

// Health
app.get('/health', (_, res) => res.json({ status: 'ok', app: 'ota-passenger', version: '1.0.0' }));

// Hotel search
app.get('/api/hotels', (req, res) => {
  const { city, checkin, checkout, guests } = req.query;
  let results = hotels;
  if (city) results = results.filter(h => h.city.toLowerCase().includes(city.toLowerCase()));
  res.json({ success: true, count: results.length, hotels: results });
});

// Hotel booking
app.post('/api/hotels/book', (req, res) => {
  const { hotelId, checkin, checkout, guests, paymentMethod } = req.body;
  const hotel = hotels.find(h => h.id === hotelId);
  if (!hotel) return res.status(404).json({ error: 'Hotel not found' });

  const nights = Math.ceil((new Date(checkout) - new Date(checkin)) / (1000 * 60 * 60 * 24));
  const booking = {
    id: `BK${Date.now()}`,
    type: 'hotel',
    hotel: hotel.name,
    checkin,
    checkout,
    guests,
    nights,
    total: hotel.price * nights,
    status: 'confirmed',
    bookingRef: `OTA${Math.random().toString(36).substr(2, 8).toUpperCase()}`,
    createdAt: new Date().toISOString()
  };

  res.status(201).json({ success: true, booking });
});

// Flight search
app.get('/api/flights', (req, res) => {
  const { from, to, date, class: flightClass } = req.query;
  let results = flights;
  if (from) results = results.filter(f => f.from.toLowerCase().includes(from.toLowerCase()));
  if (to) results = results.filter(f => f.to.toLowerCase().includes(to.toLowerCase()));
  if (flightClass) results = results.filter(f => f.class === flightClass);
  res.json({ success: true, count: results.length, flights: results });
});

// Flight booking
app.post('/api/flights/book', (req, res) => {
  const { flightId, passengers, paymentMethod } = req.body;
  const flight = flights.find(f => f.id === flightId);
  if (!flight) return res.status(404).json({ error: 'Flight not found' });

  const booking = {
    id: `BK${Date.now()}`,
    type: 'flight',
    flight: `${flight.airline} ${flight.from} → ${flight.to}`,
    depart: flight.depart,
    arrive: flight.arrive,
    passengers,
    total: flight.price * passengers,
    status: 'confirmed',
    bookingRef: `OTA${Math.random().toString(36).substr(2, 8).toUpperCase()}`,
    createdAt: new Date().toISOString()
  };

  res.status(201).json({ success: true, booking });
});

// Holiday packages
app.get('/api/packages', (req, res) => {
  res.json({ success: true, count: packages.length, packages });
});

app.post('/api/packages/book', (req, res) => {
  const { packageId, travelers, date } = req.body;
  const pkg = packages.find(p => p.id === packageId);
  if (!pkg) return res.status(404).json({ error: 'Package not found' });

  const booking = {
    id: `BK${Date.now()}`,
    type: 'package',
    package: pkg.name,
    nights: pkg.nights,
    travelers,
    total: pkg.price * travelers,
    includes: pkg.includes,
    status: 'confirmed',
    bookingRef: `OTA${Math.random().toString(36).substr(2, 8).toUpperCase()}`,
    createdAt: new Date().toISOString()
  };

  res.status(201).json({ success: true, booking });
});

// AI Trip Planner
app.post('/api/trip/plan', (req, res) => {
  const { destination, dates, budget, travelers, preferences } = req.body;

  // Simulate AI planning
  const plan = {
    id: `PLAN${Date.now()}`,
    destination,
    dates,
    budget,
    travelers,
    itinerary: [
      { day: 1, activity: 'Arrival & Hotel Check-in', suggestion: 'Best rated hotel in budget' },
      { day: 2, activity: 'City Sightseeing', suggestion: 'Top 5 attractions with tickets' },
      { day: 3, activity: 'Local Experience', suggestion: 'Food tour & culture' },
    ],
    estimatedCost: budget * travelers,
    savings: Math.floor(budget * 0.15),
    recommendations: ['Travel insurance', 'Airport transfer', 'Day trips'],
    createdAt: new Date().toISOString()
  };

  res.json({ success: true, plan });
});

// Get bookings
app.get('/api/bookings', (req, res) => {
  // In real app, fetch from database
  res.json({ success: true, bookings: [] });
});

// Corporate booking
app.post('/api/corporate/book', (req, res) => {
  const { employeeId, type, details, policyApproval } = req.body;

  const booking = {
    id: `CORP${Date.now()}`,
    employeeId,
    type,
    details,
    policyApproval: policyApproval || true,
    status: 'pending_approval',
    approvalRequired: true,
    createdAt: new Date().toISOString()
  };

  res.status(201).json({ success: true, booking });
});

// Payment
app.post('/api/payment', (req, res) => {
  const { bookingId, method, details } = req.body;

  res.json({
    success: true,
    payment: {
      id: `PAY${Date.now()}`,
      bookingId,
      method,
      status: 'completed',
      transactionId: `TXN${Math.random().toString(36).substr(2, 10).toUpperCase()}`,
      processedAt: new Date().toISOString()
    }
  });
});

app.listen(PORT, () => {
  console.log(`
╔══════════════════════════════════════════════╗
║  ✈️  OTA Passenger App — PORT ${PORT}           ║
║  AI-powered travel booking                   ║
╠══════════════════════════════════════════════╣
║  Hotels  Flights  Packages  Trip Planner   ║
╚══════════════════════════════════════════════╝
  `);
});

export default app;
