import chalk from 'chalk';
import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import inquirer from 'inquirer';
import { exec, execQuiet, getDockerCommand, loadEnv } from '../utils.js';

interface InitOptions {
  tier: string;
  force: boolean;
  docker: boolean;
}

export async function init(options: InitOptions) {
  const { tier, force, docker } = options;
  const runtimeDir = process.env.NEXHA_RUNTIME_DIR ?? resolve(process.cwd());

  console.log(chalk.blue('╔══════════════════════════════════════════╗'));
  console.log(chalk.blue('║     Nexha OS — Init (nexha-cli)       ║'));
  console.log(chalk.blue('╚══════════════════════════════════════════╝'));

  // 1. Prerequisites
  console.log(chalk.blue('[1/7] Checking prerequisites...'));
  try {
    const dockerVersion = exec('docker --version').split(',')[0];
    const dc = getDockerCommand();
    console.log(`  ${chalk.green('✓')} Docker: ${dockerVersion}`);
    console.log(`  ${chalk.green('✓')} Compose: ${dc}`);
  } catch {
    console.log(`  ${chalk.red('✗')} Docker not found — install Docker first`);
    process.exit(1);
  }

  // 2. Directories
  console.log(chalk.blue('[2/7] Creating runtime directories...'));
  for (const d of ['data', 'logs', 'certs', 'config']) {
    const dir = resolve(runtimeDir, d);
    mkdirSync(dir, { recursive: true });
    console.log(`  ${chalk.green('✓')} ${dir}`);
  }

  // 3. Environment
  console.log(chalk.blue('[3/7] Configuring environment...'));
  const envFile = resolve(runtimeDir, '.env');
  const existing = loadEnv(runtimeDir);

  if (!existsSync(envFile) || force) {
    const { name, region, email, categories } = await inquirer.prompt([
      { type: 'input', name: 'name', message: 'Nexha Name:', default: existing.NEXHA_NAME ?? 'My Nexha Network' },
      { type: 'input', name: 'region', message: 'Region (ISO code):', default: existing.NEXHA_REGION ?? 'IN' },
      { type: 'input', name: 'email', message: 'Contact Email:', default: existing.NEXHA_CONTACT_EMAIL ?? 'admin@nexha.local' },
      { type: 'input', name: 'categories', message: 'Categories (comma-separated):', default: existing.NEXHA_CATEGORIES?.replace(/[\[\]"]/g, '') ?? 'general' },
    ]);

    const envContent = `# Nexha OS Runtime — Environment (generated by nexha-cli)
NODE_ENV=development
TZ=Asia/Kolkata

# Federation
FEDERATION_URL=https://federation.nexha.io
FEDERATION_OS_REQUIRE_AUTH=false

# CorpID
CORP_ID_URL=http://corp-id:4702
CORP_ID_REQUIRE_AUTH=false

# Monitoring (Enterprise)
GRAFANA_PASSWORD=nexha

# Nexha Identity
NEXHA_NAME="${name}"
NEXHA_REGION=${region}
NEXHA_PUBLIC_KEY="fp:generate-with-nexha-keygen"
NEXHA_CONTACT_EMAIL=${email}
NEXHA_CATEGORIES='["${categories.split(',').map((c: string) => c.trim()).join('","')}"]'
`;
    writeFileSync(envFile, envContent);
    console.log(`  ${chalk.green('✓')} .env created`);
  } else {
    console.log(`  ${chalk.yellow('⚠')} .env exists (skipping — use --force to overwrite)`);
  }

  // 4. TLS certs
  console.log(chalk.blue('[4/7] Generating TLS certificates...'));
  const certFile = resolve(runtimeDir, 'certs/nexus.crt');
  if (!existsSync(certFile) || force) {
    try {
      exec(`openssl req -x509 -newkey rsa:2048 -nodes \\
  -keyout "${runtimeDir}/certs/nexus.key" \\
  -out "${runtimeDir}/certs/nexus.crt" \\
  -days 365 \\
  -subj "/CN=${process.env.USER ?? 'nexha'}/O=Nexha Network/L=${existing.NEXHA_REGION ?? 'Mumbai'}/ST=Maharashtra/C=IN"`, runtimeDir);
      console.log(`  ${chalk.green('✓')} Self-signed TLS cert generated (365 days)`);
    } catch {
      console.log(`  ${chalk.yellow('⚠')} openssl not found — skipping TLS`);
    }
  } else {
    console.log(`  ${chalk.yellow('⚠')} Certs exist (skipping — use --force to regenerate)`);
  }

  // 5. Prometheus config
  console.log(chalk.blue('[5/7] Verifying config...'));
  const prometheusSrc = resolve(runtimeDir, 'config/prometheus.yml');
  if (existsSync(prometheusSrc)) {
    console.log(`  ${chalk.green('✓')} prometheus.yml found`);
  } else {
    console.log(`  ${chalk.yellow('⚠')} prometheus.yml not found (normal for Lite tier)`);
  }

  // 6. Docker network
  console.log(chalk.blue('[6/7] Verifying Docker network...'));
  if (execQuiet('docker network inspect nexha-internal > /dev/null 2>&1')) {
    console.log(`  ${chalk.green('✓')} Network 'nexha-internal' exists`);
  } else {
    console.log(`  ${chalk.yellow('  ')} Network will be created by Compose`);
  }

  // 7. Build & start
  if (docker) {
    console.log(chalk.blue('[7/7] Building & starting containers...'));
    const dc = getDockerCommand();
    try {
      exec(`${dc} --profile ${tier} build`, runtimeDir);
      exec(`${dc} --profile ${tier} up -d --remove-orphans`, runtimeDir);
      console.log(`  ${chalk.green('✓')} Containers started (${tier} tier)`);

      // Auto-provision
      console.log(chalk.blue('[8/8] Running auto-provisioning...'));
      try {
        exec(`bash "${resolve(runtimeDir, 'scripts/provision.sh')}"`, runtimeDir);
      } catch (err) {
        console.log(`  ${chalk.yellow('⚠')} Provisioning had issues (may be expected on first run):`);
        console.log(`  ${String(err)}`);
      }

      // Brief wait then show status
      await new Promise(r => setTimeout(r, 2000));
      try {
        exec(`${dc} --profile ${tier} ps --format "{{.Name}}: {{.Status}}"`, runtimeDir);
      } catch { /* ok */ }
    } catch (err) {
      console.log(`  ${chalk.red('✗')} Failed to start containers:`);
      console.log(`  ${String(err)}`);
    }
  } else {
    console.log(chalk.blue('[7/7] Docker start skipped (--no-docker)'));
    console.log('');
    console.log(`  ${chalk.yellow('⚠')} After starting containers manually, run:`);
    console.log(`     bash scripts/provision.sh`);
  }

  console.log('');
  console.log(chalk.green('╔══════════════════════════════════════════╗'));
  console.log(chalk.green('║     Nexha OS Initialised!                ║'));
  console.log(chalk.green('╠══════════════════════════════════════════╣'));
  console.log(chalk.green('║  Gateway:   http://localhost:5002         ║'));
  console.log(chalk.green('║  CorpID:   http://localhost:4702         ║'));
  console.log(chalk.green('║  MemoryOS: http://localhost:4703         ║'));
  console.log(chalk.green('║  TwinOS:   http://localhost:4705         ║'));
  console.log(chalk.green('╠══════════════════════════════════════════╣'));
  console.log(chalk.green('║  Next steps:                              ║'));
  console.log(chalk.green('║  1. nexha register                       ║'));
  console.log(chalk.green('║  2. nexha status                         ║'));
  console.log(chalk.green('╚══════════════════════════════════════════╝'));
}
