/**
 * HOJAI Deploy Pipeline
 * Port: 4540
 * Compiles templates → code → deploys to cloud
 */
import express from 'express';
import cors from 'cors';
import { v4 as uuidv4 } from 'uuid';
import { execSync } from 'child_process';
import { writeFileSync, mkdirSync, existsSync, cpSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PORT = process.env.PORT || 4540;
const DEPLOY_DIR = process.env.DEPLOY_DIR || '/tmp/hojai-deploys';
const BASE_DOMAIN = process.env.BASE_DOMAIN || 'hojai.app';

const app = express();
app.use(cors(), express.json());

// Deployments store
const deployments = new Map();

// Template code generators
function generateAppCode(template, companyName) {
  return `
// ${companyName} - Generated by HOJAI Studio
// Template: ${template}

const express = require('express');
const app = express();

app.use(express.json());

app.get('/health', (req, res) => {
  res.json({ status: 'ok', company: '${companyName}', template: '${template}' });
});

app.get('/api/info', (req, res) => {
  res.json({
    company: '${companyName}',
    template: '${template}',
    version: '1.0.0',
    deployed: new Date().toISOString()
  });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(\`${companyName} running on \${PORT}\`));
`;
}

function generateDockerfile(companyName) {
  return `FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --production
COPY . .
EXPOSE 3000
CMD ["node", "src/index.js"]`;
}

function generatePackageJson(companyName, template) {
  return JSON.stringify({
    name: companyName.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    scripts: { start: 'node src/index.js' },
    dependencies: { express: '^4.18.2' }
  }, null, 2);
}

function generateReadme(companyName, template, apps) {
  return `# ${companyName}

Built with HOJAI Studio — ${template} template

## Apps
${apps.map(a => `- ${a.name}: https://${a.subdomain}.${BASE_DOMAIN}`).join('\n')}

## AI Workers
Hired from BAM: https://app.hojai.ai/bam

## Deploy Status
✅ Deployed: ${new Date().toISOString()}
`;
}

// Deploy endpoint
app.post('/deploy', async (req, res) => {
  const { companyName, template, config } = req.body;

  if (!companyName || !template) {
    return res.status(400).json({ error: 'companyName and template required' });
  }

  const deploymentId = uuidv4();
  const slug = companyName.toLowerCase().replace(/[^a-z0-9]/g, '-');

  // Create deployment directory
  const deployPath = `${DEPLOY_DIR}/${slug}`;
  mkdirSync(`${deployPath}/apps/passenger/src`, { recursive: true });
  mkdirSync(`${deployPath}/apps/driver/src`, { recursive: true });
  mkdirSync(`${deployPath}/apps/admin/src`, { recursive: true });

  // Generate code for each app
  const apps = [
    { name: `${companyName} Passenger`, subdomain: `${slug}-passenger`, type: 'passenger' },
    { name: `${companyName} Driver`, subdomain: `${slug}-driver`, type: 'driver' },
    { name: `${companyName} Admin`, subdomain: `${slug}-admin`, type: 'admin' }
  ];

  for (const appDef of apps) {
    // Generate package.json
    writeFileSync(
      `${deployPath}/apps/${appDef.type}/package.json`,
      generatePackageJson(companyName, template)
    );

    // Generate main code
    writeFileSync(
      `${deployPath}/apps/${appDef.type}/src/index.js`,
      generateAppCode(template, companyName)
    );

    // Generate Dockerfile
    writeFileSync(
      `${deployPath}/apps/${appDef.type}/Dockerfile`,
      generateDockerfile(companyName)
    );
  }

  // Generate README
  writeFileSync(
    `${deployPath}/README.md`,
    generateReadme(companyName, template, apps)
  );

  // Start containers (simulated)
  const status = {
    id: deploymentId,
    company: companyName,
    template,
    slug,
    apps,
    urls: apps.map(a => ({
      name: a.name,
      url: `https://${a.subdomain}.${BASE_DOMAIN}`,
      status: 'provisioning'
    })),
    status: 'building',
    startedAt: new Date().toISOString()
  };

  deployments.set(deploymentId, status);

  // Simulate deployment process
  setTimeout(() => {
    const d = deployments.get(deploymentId);
    if (d) {
      d.urls = d.urls.map(u => ({ ...u, status: 'live' }));
      d.status = 'live';
      d.deployedAt = new Date().toISOString();
    }
  }, 5000);

  res.status(201).json({
    success: true,
    deployment: {
      id: deploymentId,
      company: companyName,
      slug,
      status: 'building',
      urls: apps.map(a => ({
        name: a.name,
        url: `https://${a.subdomain}.${BASE_DOMAIN}`
      })),
      dashboard: `https://studio.hojai.ai/deployments/${deploymentId}`
    }
  });
});

// Get deployment status
app.get('/deploy/:id', (req, res) => {
  const deployment = deployments.get(req.params.id);
  if (!deployment) return res.status(404).json({ error: 'Deployment not found' });
  res.json({ success: true, deployment });
});

// List deployments
app.get('/deployments', (_, res) => {
  const all = Array.from(deployments.values());
  res.json({ success: true, count: all.length, deployments: all });
});

// Health
app.get('/health', (_, res) => res.json({ status: 'ok', service: 'deploy-pipeline' }));

app.listen(PORT, () => console.log(`
╔══════════════════════════════════════════╗
║  Deploy Pipeline — PORT ${PORT}            ║
║  Template → Code → Deploy             ║
╠══════════════════════════════════════╣
║  POST /deploy     — Deploy company    ║
║  GET  /deploy/:id — Check status     ║
║  GET  /deployments — List all         ║
╚══════════════════════════════════════╝
`));

export default app;
