/**
 * Template Compiler v1.0
 * Compiles JSON templates into running apps
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, cpSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { v4 as uuidv4 } from 'uuid';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = join(__dirname, '../../starters');

// ── Code Generators ──────────────────────────────────────────────

function generatePassengerApp(template) {
  return `
// Passenger App - Generated by HOJAI Studio
// Template: ${template.id}

import React from 'react';
import { View, Text, Button, TextInput, StyleSheet } from 'react-native';

export default function PassengerApp({ navigation }) {
  const [destination, setDestination] = React.useState('');
  const [pickup, setPickup] = React.useState('${template.config?.home || 'Current Location'}');

  const bookRide = async () => {
    const res = await fetch('http://localhost:4600/api/v1/book', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ destination, pickup, vehicleType: 'auto' })
    });
    const data = await res.json();
    // Navigate to tracking screen
  };

  return (
    <View style={styles.container}>
      <Text style={styles.title}>${template.name}</Text>
      <TextInput
        placeholder="Where to?"
        value={destination}
        onChangeText={setDestination}
        style={styles.input}
      />
      <Text style={styles.label}>Pickup: {pickup}</Text>
      <Button title="Book Ride" onPress={bookRide} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, padding: 20, backgroundColor: '#fff' },
  title: { fontSize: 24, fontWeight: 'bold', marginBottom: 20 },
  input: { borderWidth: 1, padding: 12, borderRadius: 8, marginBottom: 12 },
  label: { marginBottom: 8, color: '#666' }
});
`;
}

function generateDriverApp(template) {
  return `
// Driver App - Generated by HOJAI Studio
// Template: ${template.id}

import React from 'react';
import { View, Text, Button, StyleSheet } from 'react-native';

export default function DriverApp({ navigation }) {
  const [online, setOnline] = React.useState(false);
  const [earnings, setEarnings] = React.useState(0);

  return (
    <View style={styles.container}>
      <Text style={styles.earnings}>Today: ₹{earnings}</Text>
      <Button
        title={online ? 'Go Offline' : 'Go Online'}
        onPress={() => setOnline(!online)}
        color={online ? '#ef4444' : '#22c55e'}
      />
      {online && <Text style={styles.status}>Looking for rides...</Text>}
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, padding: 20, justifyContent: 'center', alignItems: 'center' },
  earnings: { fontSize: 32, fontWeight: 'bold', marginBottom: 20 },
  status: { marginTop: 20, color: '#666' }
});
`;
}

function generateAdminDashboard(template) {
  return `
// Admin Dashboard - Generated by HOJAI Studio
// Template: ${template.id}

import React, { useState, useEffect } from 'react';

export default function AdminDashboard() {
  const [stats, setStats] = useState({ trips: 0, drivers: 0, revenue: 0 });

  useEffect(() => {
    fetch('http://localhost:4600/api/v1/stats')
      .then(r => r.json())
      .then(setStats);
  }, []);

  return (
    <div style={{ padding: 20 }}>
      <h1>${template.name} Admin</h1>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 20 }}>
        <DashboardCard title="Total Trips" value={stats.trips} />
        <DashboardCard title="Active Drivers" value={stats.drivers} />
        <DashboardCard title="Revenue" value={'₹' + stats.revenue} />
      </div>
    </div>
  );
}

function DashboardCard({ title, value }) {
  return (
    <div style={{
      background: '#1e293b',
      padding: 20,
      borderRadius: 12,
      textAlign: 'center'
    }}>
      <div style={{ fontSize: 32, fontWeight: 'bold', color: '#fff' }}>{value}</div>
      <div style={{ color: '#94a3b8', marginTop: 8 }}>{title}</div>
    </div>
  );
}
`;
}

function generateAgentsIndex(agents) {
  return `
// AI Agents Index - Generated by HOJAI Studio
// Total agents: ${agents.length}

${agents.map(a => `
export const ${a.role.replace(/\s+/g, '')}Agent = {
  id: '${a.id || uuidv4()}',
  role: '${a.role}',
  salary: ${a.salary},
  model: '${a.model}',
  capabilities: ${JSON.stringify(a.skills || [])},
  memory: ${JSON.stringify(a.memory || [])},
  status: 'active'
};`).join('\n')}
`;
}

function generateFlows(flows) {
  return `
// Flows Index - Generated by HOJAI Studio
// Total flows: ${flows.length}

${flows.map(f => `
export const ${f.id.replace(/_/g, '')}Flow = {
  id: '${f.id}',
  name: '${f.name}',
  trigger: '${f.trigger}',
  status: 'active'
};`).join('\n')}
`;
}

function generatePolicies(policies) {
  return `
// Policies - Generated by HOJAI Studio

export const POLICIES = ${JSON.stringify(policies, null, 2)};

// Policy Engine
export function evaluatePolicy(policy, context) {
  const { rule, action, notification } = policy;
  // Simple rule evaluation
  // In production, use a proper rule engine
  return { action, notification, passed: true };
}
`;
}

function generatePackage(name, deps = {}) {
  return JSON.stringify({
    name: name.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    dependencies: {
      'express': '^4.18.2',
      'cors': '^2.8.5',
      'uuid': '^9.0.0',
      ...deps
    },
    scripts: {
      start: 'node src/index.js'
    }
  }, null, 2);
}

function generateIndex(companyName, agents, flows) {
  return `
// ${companyName} - Generated by HOJAI Studio
// Powered by HOJAI Cloud + Nexha + DO

const PORT = process.env.PORT || 3000;
import express from 'express';
import cors from 'cors';

const app = express();
app.use(cors(), express.json());

// Health
app.get('/health', (_, res) => res.json({ status: 'ok', company: '${companyName}', template: '${flows[0]?.template || 'custom' }));

// AI Agents endpoint
app.get('/api/agents', (_, res) => res.json({
  agents: ${JSON.stringify(agents.map(a => ({ role: a.role, salary: a.salary }))},
  total: ${agents.reduce((s, a) => s + a.salary, 0)}/month
}));

// Flows endpoint
app.get('/api/flows', (_, res) => res.json({
  flows: ${JSON.stringify(flows.map(f => ({ id: f.id, name: f.name }))}
}));

// ${flows[0]?.id || 'main'} flow
app.post('/api/${flows[0]?.id || 'execute'}', (req, res) => {
  res.json({ success: true, flow: '${flows[0]?.name}', status: 'running' });
});

app.listen(PORT, () => console.log(\`
╔══════════════════════════════════════════╗
║ ${companyName.padEnd(32)} ║
║ AI-powered by HOJAI Studio          ║
╚══════════════════════════════════╝
\`));
`;
}

// ── Compiler ────────────────────────────────────────────────────────

export function compileTemplate({ name, template, outputDir, options = {} }) {
  const companyName = name || 'My Company';
  const out = outputDir || \`./output/\${companyName.toLowerCase().replace(/\s+/g, '-')}\`;

  // Create directory structure
  mkdirSync(out, { recursive: true });
  mkdirSync(\`\${out}/apps/passenger-app\` , { recursive: true });
  mkdirSync(\`\${out}/apps/driver-app\` , { recursive: true });
  mkdirSync(\`\${out}/apps/admin-dashboard\`, { recursive: true });
  mkdirSync(\`\${out}/agents\`, { recursive: true });
  mkdirSync(\`\${out}/flows\`, { recursive: true });
  mkdirSync(\`\${out}/policies\`, { recursive: true });
  mkdirSync(\`\${out}/backend/src\`, { recursive: true });

  // Generate apps
  writeFileSync(\`\${out}/apps/passenger-app/App.tsx\`, generatePassengerApp(template));
  writeFileSync(\`\${out}/apps/driver-app/App.tsx\`, generateDriverApp(template));
  writeFileSync(\`\${out}/apps/admin-dashboard/App.tsx\`, generateAdminDashboard(template));

  // Generate agents index
  const agents = template.crew?.ai_workers || [];
  writeFileSync(\`\${out}/agents/index.js\`, generateAgentsIndex(agents));
  writeFileSync(\`\${out}/agents/package.json\`, generatePackage('agents'));

  // Generate flows
  const flows = template.flows || [];
  writeFileSync(\`\${out}/flows/index.js\`, generateFlows(flows));

  // Generate policies
  const policies = template.policies || [];
  writeFileSync(\`\${out}/policies/index.js\`, generatePolicies(policies));

  // Generate backend
  writeFileSync(\`\${out}/backend/src/index.js\`, generateIndex(companyName, agents, flows));
  writeFileSync(\`\${out}/backend/package.json\`, generatePackage(companyName));

  // Generate mobile package.json
  writeFileSync(\`\${out}/apps/passenger-app/package.json\`, JSON.stringify({
    name: \`\${companyName.toLowerCase()}-passenger\`,
    version: '1.0.0',
    dependencies: { 'expo': '^49.0.0', 'react-native': '0.72.0' }
  }, null, 2));

  return {
    company: companyName,
    output: out,
    agents: agents.length,
    flows: flows.length,
    policies: policies.length
  };
}
