import { describe, it, expect } from 'vitest';
describe('Memory Learning', () => {
  it('records success', () => { const o = { success: true }; expect(o.success).toBe(true); });
  it('records failure', () => { const o = { success: false }; expect(o.success).toBe(false); });
  it('tracks rate', () => { const o = [{ success: true }, { success: true }, { success: false }, { success: true }]; expect(o.filter(x => x.success).length / o.length).toBe(0.75); });
  it('reinforce rule', () => { const r = { action: 'reinforce', confidence: 0.6 }; expect(r.action).toBe('reinforce'); });
  it('weaken rule', () => { const r = { action: 'weaken', confidence: 0.4 }; expect(r.action).toBe('weaken'); });
  it('increments count', () => { let c = 5; c++; expect(c).toBe(6); });
  it('groups failures', () => { const f = [{ m: 'm1' }, { m: 'm1' }, { m: 'm2' }]; const g = {}; for (const x of f) g[x.m] = (g[x.m] || 0) + 1; expect(g.m1).toBe(2); });
  it('repeated failures', () => { const g = { m1: 3, m2: 1 }; expect(Object.entries(g).filter(([_, c]) => c >= 2).length).toBe(1); });
  it('failure rate', () => { expect(30 / 100).toBe(0.3); });
  it('confidence issue', () => { expect(0.6 < 0.7).toBe(true); });
  it('no issue', () => { expect(0.85 < 0.7).toBe(false); });
  it('reinforces', () => { const m = { confidence: 0.5 }; m.confidence = Math.min(1, m.confidence + 0.05); expect(m.confidence).toBe(0.55); });
  it('weakens', () => { const m = { confidence: 0.5 }; m.confidence = Math.max(0, m.confidence - 0.1); expect(m.confidence).toBe(0.4); });
  it('caps at 1', () => { const m = { confidence: 0.95 }; m.confidence = Math.min(1, m.confidence + 0.1); expect(m.confidence).toBe(1); });
  it('floors at 0', () => { const m = { confidence: 0.05 }; m.confidence = Math.max(0, m.confidence - 0.1); expect(m.confidence).toBe(0); });
  it('no outcomes', () => { const o = []; expect(o.length > 0 ? o.filter(x => x.success).length / o.length : 0).toBe(0); });
  it('all success', () => { const o = [{ success: true }, { success: true }]; expect(o.filter(x => x.success).length / o.length).toBe(1); });
  it('all fail', () => { const o = [{ success: false }, { success: false }]; expect(o.filter(x => x.success).length / o.length).toBe(0); });
});
