// Vitest setup - disable auth for all tests
// This file runs before all tests

// Set auth env vars to disable authentication in tests
// Pattern: const NAME_REQUIRE_AUTH = (process.env.NAME_REQUIRE_AUTH ?? 'true').toLowerCase() !== 'false';
const authEnvVars = [
  'AGENT_BUILDER_REQUIRE_AUTH',
  'AI_REGISTRY_REQUIRE_AUTH',
  'BACKGROUND_AGENTS_REQUIRE_AUTH',
  'BEHAVIOR_INTELLIGENCE_REQUIRE_AUTH',
  'BUDGETING_REQUIRE_AUTH',
  'COMPLIANCE_REQUIRE_AUTH',
  'CONSENT_REQUIRE_AUTH',
  'DECISION_INTELLIGENCE_REQUIRE_AUTH',
  'EXECUTION_OS_REQUIRE_AUTH',
  'FLOW_REQUIRE_AUTH',
  'HOJAI_CLOUD_REQUIRE_AUTH',
  'HOJAI_GOALOS_REQUIRE_AUTH',
  'INTELLIGENCE_REQUIRE_AUTH',
  'INTENT_ENGINE_REQUIRE_AUTH',
  'KNOWLEDGE_EXTRACTION_REQUIRE_AUTH',
  'KNOWLEDGE_MARKETPLACE_REQUIRE_AUTH',
  'LEGAL_REQUIRE_AUTH',
  'LOCALIZATION_REQUIRE_AUTH',
  'MISSION_OS_REQUIRE_AUTH',
  'MULTI_AGENT_RUNTIME_REQUIRE_AUTH',
  'POLICYOS_REQUIRE_AUTH',
  'PROACTIVE_ENGINE_REQUIRE_AUTH',
  'REASONING_ENGINE_REQUIRE_AUTH',
  'REFLECTION_ENGINE_REQUIRE_AUTH',
  'REQUIRE_AUTH',
  'RESEARCH_REQUIRE_AUTH',
  'SADA_REQUIRE_AUTH',
  'SKILLOS_REQUIRE_AUTH',
  'TENANT_MANAGER_REQUIRE_AUTH',
  'TRAVEL_REQUIRE_AUTH',
  'WIDGET_REQUIRE_AUTH',
];

for (const envVar of authEnvVars) {
  process.env[envVar] = 'false';
}
