/**
 * Journal Model - AI-powered journaling
 */

export class Journal {
  constructor(data) {
    this.id = data.id || uuidv4();
    this.userId = data.userId;
    this.type = data.type || 'daily'; // daily, reflection, gratitude, milestone, emotional
    this.date = data.date || new Date().toISOString().split('T')[0];
    this.title = data.title || '';
    this.content = data.content || '';
    this.mood = data.mood || null; // mood at time of writing
    this.moodScore = data.moodScore || 5;
    this.highlights = data.highlights || []; // best parts of the day
    this.challenges = data.challenges || []; // difficulties faced
    this.gratitude = data.gratitude || []; // things grateful for
    this.lessons = data.lessons || []; // what was learned
    this.goals = data.goals || []; // goals mentioned
    this.people = data.people || []; // people mentioned
    this.activities = data.activities || []; // activities done
    this.energy = data.energy || null;
    this.sleep = data.sleep || null;
    this.sentiment = data.sentiment || 'neutral'; // positive, neutral, negative
    this.aiInsights = data.aiInsights || []; // AI-generated insights
    this.autoGenerated = data.autoGenerated || false;
    this.voiceNote = data.voiceNote || null; // voice note URL
    this.tags = data.tags || [];
    this.createdAt = data.createdAt || new Date().toISOString();
    this.updatedAt = data.updatedAt || new Date().toISOString();
  }

  toJSON() {
    return {
      id: this.id,
      userId: this.userId,
      type: this.type,
      date: this.date,
      title: this.title,
      content: this.content,
      mood: this.mood,
      moodScore: this.moodScore,
      highlights: this.highlights,
      challenges: this.challenges,
      gratitude: this.gratitude,
      lessons: this.lessons,
      goals: this.goals,
      people: this.people,
      activities: this.activities,
      energy: this.energy,
      sleep: this.sleep,
      sentiment: this.sentiment,
      aiInsights: this.aiInsights,
      autoGenerated: this.autoGenerated,
      voiceNote: this.voiceNote,
      tags: this.tags,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt
    };
  }
}

// Journal types
export const JOURNAL_TYPES = {
  daily: {
    name: 'Daily Journal',
    description: 'Regular daily reflection',
    prompts: [
      'How was your day?',
      'What was the best part of today?',
      'What challenged you today?',
      'What are you grateful for today?',
      'What did you learn today?'
    ]
  },
  reflection: {
    name: 'Deep Reflection',
    description: 'Introspective thoughts and feelings',
    prompts: [
      'What is on your mind?',
      'How are you really feeling?',
      'What would you like to change?',
      'What patterns do you notice in your life?'
    ]
  },
  gratitude: {
    name: 'Gratitude Journal',
    description: 'Focus on appreciation',
    prompts: [
      'What are you most grateful for today?',
      'Who made a positive impact on your life recently?',
      'What small thing brought you joy?',
      'What would you miss if it was gone?'
    ]
  },
  milestone: {
    name: 'Milestone',
    description: 'Record important achievements',
    prompts: [
      'What did you accomplish?',
      'How did you feel about this achievement?',
      'Who supported you?',
      'What comes next?'
    ]
  },
  emotional: {
    name: 'Emotional Processing',
    description: 'Work through difficult emotions',
    prompts: [
      'What emotion are you experiencing?',
      'Where do you feel this in your body?',
      'What triggered this feeling?',
      'What do you need right now?'
    ]
  },
  goalProgress: {
    name: 'Goal Progress',
    description: 'Track progress on goals',
    prompts: [
      'What goal are you working on?',
      'What progress did you make?',
      'What obstacles did you face?',
      'What will you do differently?'
    ]
  }
};

// Generate journal summary
export const generateJournalSummary = (journal) => {
  const summaries = {
    daily: {
      emoji: '📝',
      template: 'Today was a {sentiment} day. The highlight was {highlight}. Main challenge: {challenge}. Grateful for: {gratitude}.'
    },
    reflection: {
      emoji: '💭',
      template: 'Deep thoughts about {topic}. Feeling {mood}. Key insight: {insight}.'
    },
    gratitude: {
      emoji: '🙏',
      template: 'Grateful for {items}. Feeling appreciated and blessed.'
    },
    milestone: {
      emoji: '🏆',
      template: 'Achieved {achievement}! Feeling proud and motivated.'
    },
    emotional: {
      emoji: '❤️',
      template: 'Processing {emotion}. This is valid and important.'
    }
  };

  return summaries[journal.type] || summaries.daily;
};

// Generate AI insights from journal
export const analyzeJournalInsights = (journals) => {
  if (!journals || journals.length < 3) {
    return {
      insights: [],
      patterns: [],
      suggestions: []
    };
  }

  const insights = [];
  const patterns = [];
  const suggestions = [];

  // Analyze mood trends
  const moodScores = journals.map(j => j.moodScore || 5);
  const avgMood = moodScores.reduce((a, b) => a + b, 0) / moodScores.length;

  if (avgMood < 4) {
    insights.push("You've been going through a tough period. Your feelings are valid.");
    suggestions.push("Consider talking to someone you trust about how you've been feeling.");
  } else if (avgMood > 7) {
    insights.push("You're in a great space! This positive energy is wonderful.");
  }

  // Analyze gratitude patterns
  const gratitudeCount = journals.filter(j => j.gratitude && j.gratitude.length > 0).length;
  if (gratitudeCount < journals.length / 3) {
    patterns.push("You could benefit from more gratitude practice.");
    suggestions.push("Try writing 3 things you're grateful for each day.");
  }

  // Analyze sleep patterns
  const sleepEntries = journals.filter(j => j.sleep);
  if (sleepEntries.length > 0) {
    const avgSleep = sleepEntries.reduce((a, j) => a + (j.sleep || 0), 0) / sleepEntries.length;
    if (avgSleep < 6) {
      patterns.push("Your sleep has been below recommended levels.");
      suggestions.push("Aim for 7-9 hours of sleep for better mental health.");
    }
  }

  // Analyze common themes
  const allTags = journals.flatMap(j => j.tags || []);
  const tagCounts = {};
  allTags.forEach(tag => {
    tagCounts[tag] = (tagCounts[tag] || 0) + 1;
  });
  const topTags = Object.entries(tagCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([tag]) => tag);

  if (topTags.length > 0) {
    patterns.push(`You often journal about: ${topTags.join(', ')}`);
  }

  return { insights, patterns, suggestions };
};
