/**
 * OTA Admin Dashboard - Generated by HOJAI Studio
 */
import express from 'express';
import cors from 'cors';

const app = express();

// ── Internal Auth ────────────────────────────────────────────────
function requireInternal(req, res, next) {
  const token = req.headers['x-internal-token'];
  const expected = process.env.INTERNAL_SERVICE_TOKEN;
  if (token && expected && token === expected) {
    req.user = { type: 'service', id: 'internal' };
    return next();
  }
  return res.status(401).json({ error: 'Unauthorized' });
}

app.use(cors(), express.json());
const PORT = process.env.PORT || 3001;

app.get('/health', (_, res) => res.json({ status: 'ok', app: 'ota-admin' }));

// Dashboard stats
app.get('/api/stats', (_, res) => {
  res.json({
    success: true,
    stats: {
      todayBookings: 147,
      revenue: 2450000,
      activeHotels: 234,
      activeFlights: 89,
      pendingApprovals: 12,
      revenueTrend: '+18%',
      bookingsTrend: '+24%'
    }
  });
});

// Hotel management
app.get('/api/hotels', (_, res) => {
  res.json({ success: true, hotels: [] });
});

app.post('/api/hotels', requireInternal, (req, res) => {
  res.status(201).json({ success: true, hotel: { id: Date.now(), ...req.body } });
});

// Flight management
app.get('/api/flights', (_, res) => {
  res.json({ success: true, flights: [] });
});

// Partner management
app.get('/api/partners', (_, res) => {
  res.json({ success: true, partners: [] });
});

// Corporate accounts
app.get('/api/corporate', (_, res) => {
  res.json({ success: true, accounts: [] });
});

// AI Analytics
app.get('/api/analytics', (_, res) => {
  res.json({
    success: true,
    analytics: {
      bookingRate: 0.78,
      conversionRate: 0.24,
      avgBookingValue: 18500,
      topDestinations: ['Goa', 'Kerala', 'Jaipur', 'Manali', 'Dubai'],
      revenueByType: { hotel: 60, flight: 25, package: 15 }
    }
  });
});

app.listen(PORT, () => console.log(`\n✈️  OTA Admin — PORT ${PORT}\n`));
export default app;
