#!/usr/bin/env node
/**
 * OpenAPI spec generator for HOJAI AI services
 * Generates swagger.json with all 15 services
 */

const fs = require('fs');
const path = require('path');

const services = [
  { name: 'Agent OS', port: 4892, phase: 11, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'GET', path: '/ready', summary: 'Ready check' },
    { method: 'GET', path: '/api/agents', summary: 'List agents' },
    { method: 'POST', path: '/api/agents', summary: 'Create agent' },
    { method: 'GET', path: '/api/agents/:id', summary: 'Get agent' },
    { method: 'PUT', path: '/api/agents/:id', summary: 'Update agent' },
    { method: 'DELETE', path: '/api/agents/:id', summary: 'Delete agent' },
    { method: 'POST', path: '/api/agents/:id/start', summary: 'Start agent' },
    { method: 'POST', path: '/api/agents/:id/stop', summary: 'Stop agent' },
    { method: 'POST', path: '/api/agents/:id/execute', summary: 'Execute task' },
    { method: 'GET', path: '/api/agents/:id/executions/:execId', summary: 'Get execution' },
    { method: 'GET', path: '/api/agents/:id/health', summary: 'Agent health' },
  ]},
  { name: 'Personalization', port: 4893, phase: 21, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'GET', path: '/api/profiles', summary: 'List profiles' },
    { method: 'POST', path: '/api/profiles', summary: 'Create profile' },
    { method: 'GET', path: '/api/profiles/:userId', summary: 'Get profile' },
    { method: 'PUT', path: '/api/profiles/:userId', summary: 'Update profile' },
    { method: 'DELETE', path: '/api/profiles/:userId', summary: 'Delete profile' },
    { method: 'POST', path: '/api/preferences/:userId/track', summary: 'Track preference' },
    { method: 'GET', path: '/api/recommendations/:userId', summary: 'Get recommendations' },
    { method: 'GET', path: '/api/segments', summary: 'List segments' },
  ]},
  { name: 'AI Economy', port: 4894, phase: 22, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'GET', path: '/api/listings', summary: 'List marketplace listings' },
    { method: 'POST', path: '/api/listings', summary: 'Create listing' },
    { method: 'GET', path: '/api/listings/:id', summary: 'Get listing' },
    { method: 'PUT', path: '/api/listings/:id', summary: 'Update listing' },
    { method: 'DELETE', path: '/api/listings/:id', summary: 'Delete listing' },
    { method: 'POST', path: '/api/transactions/purchase', summary: 'Purchase listing' },
    { method: 'GET', path: '/api/transactions', summary: 'List transactions' },
    { method: 'GET', path: '/api/wallets/:ownerId', summary: 'Get wallet' },
    { method: 'POST', path: '/api/wallets/:ownerId/topup', summary: 'Top up wallet' },
    { method: 'GET', path: '/api/analytics', summary: 'Get analytics' },
  ]},
  { name: 'Governance', port: 4895, phase: 23, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'GET', path: '/api/policies', summary: 'List policies' },
    { method: 'POST', path: '/api/policies', summary: 'Create policy' },
    { method: 'GET', path: '/api/policies/:id', summary: 'Get policy' },
    { method: 'PUT', path: '/api/policies/:id', summary: 'Update policy' },
    { method: 'DELETE', path: '/api/policies/:id', summary: 'Delete policy' },
    { method: 'POST', path: '/api/evaluate', summary: 'Evaluate entity' },
    { method: 'POST', path: '/api/evaluate/bulk', summary: 'Bulk evaluate' },
    { method: 'GET', path: '/api/audit', summary: 'Get audit trail' },
    { method: 'GET', path: '/api/reports/compliance', summary: 'Compliance report' },
  ]},
  { name: 'Planning Engine', port: 4896, phase: 14, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'GET', path: '/api/plans', summary: 'List plans' },
    { method: 'POST', path: '/api/plans', summary: 'Create plan' },
    { method: 'GET', path: '/api/plans/:id', summary: 'Get plan' },
    { method: 'PUT', path: '/api/plans/:id', summary: 'Update plan' },
    { method: 'DELETE', path: '/api/plans/:id', summary: 'Delete plan' },
    { method: 'POST', path: '/api/decompose', summary: 'Decompose goal' },
    { method: 'POST', path: '/api/validate', summary: 'Validate plan' },
    { method: 'POST', path: '/api/plans/:id/execute', summary: 'Execute plan' },
    { method: 'POST', path: '/api/toposort', summary: 'Topological sort' },
    { method: 'POST', path: '/api/cycles', summary: 'Detect cycles' },
  ]},
  { name: 'Multi-Modal', port: 4897, phase: 27, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'POST', path: '/api/detect', summary: 'Detect media type' },
    { method: 'GET', path: '/api/formats', summary: 'Get supported formats' },
    { method: 'POST', path: '/api/image/process', summary: 'Process image' },
    { method: 'POST', path: '/api/audio/process', summary: 'Process audio' },
    { method: 'POST', path: '/api/video/process', summary: 'Process video' },
    { method: 'POST', path: '/api/ocr', summary: 'OCR processing' },
    { method: 'POST', path: '/api/transcribe', summary: 'Transcribe audio' },
    { method: 'GET', path: '/api/jobs', summary: 'List jobs' },
    { method: 'GET', path: '/api/jobs/:id', summary: 'Get job' },
    { method: 'POST', path: '/api/batch', summary: 'Batch process' },
  ]},
  { name: 'AIOps', port: 4898, phase: 26, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'GET', path: '/api/metrics', summary: 'Query metrics' },
    { method: 'POST', path: '/api/metrics', summary: 'Ingest metric' },
    { method: 'GET', path: '/api/metrics/summary', summary: 'Metric summary' },
    { method: 'GET', path: '/api/alerts', summary: 'List alerts' },
    { method: 'POST', path: '/api/alerts', summary: 'Create alert' },
    { method: 'POST', path: '/api/alerts/:id/acknowledge', summary: 'Acknowledge alert' },
    { method: 'POST', path: '/api/alerts/:id/resolve', summary: 'Resolve alert' },
    { method: 'POST', path: '/api/alerts/:id/snooze', summary: 'Snooze alert' },
    { method: 'GET', path: '/api/incidents', summary: 'List incidents' },
    { method: 'POST', path: '/api/incidents', summary: 'Create incident' },
    { method: 'GET', path: '/api/status', summary: 'System status' },
  ]},
  { name: 'Memory Lifecycle', port: 4899, phase: 39, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'GET', path: '/api/memories', summary: 'List memories' },
    { method: 'POST', path: '/api/memories', summary: 'Create memory' },
    { method: 'GET', path: '/api/memories/:id', summary: 'Get memory' },
    { method: 'PUT', path: '/api/memories/:id', summary: 'Update memory' },
    { method: 'DELETE', path: '/api/memories/:id', summary: 'Delete memory' },
    { method: 'GET', path: '/api/memories/expired', summary: 'Get expired memories' },
    { method: 'POST', path: '/api/compact', summary: 'Compact memories' },
    { method: 'POST', path: '/api/prune', summary: 'Prune low-confidence' },
    { method: 'POST', path: '/api/archive', summary: 'Archive old memories' },
    { method: 'POST', path: '/api/gdpr/delete', summary: 'GDPR deletion' },
    { method: 'GET', path: '/api/stats', summary: 'Memory statistics' },
  ]},
  { name: 'Knowledge Registry', port: 4900, phase: 36, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'GET', path: '/api/assets', summary: 'List knowledge assets' },
    { method: 'POST', path: '/api/assets', summary: 'Create asset' },
    { method: 'GET', path: '/api/assets/:id', summary: 'Get asset' },
    { method: 'PUT', path: '/api/assets/:id', summary: 'Update asset' },
    { method: 'DELETE', path: '/api/assets/:id', summary: 'Delete asset' },
    { method: 'POST', path: '/api/assets/:id/versions', summary: 'Create version' },
    { method: 'GET', path: '/api/taxonomy', summary: 'List taxonomy' },
    { method: 'POST', path: '/api/search', summary: 'Search assets' },
    { method: 'GET', path: '/api/stats', summary: 'Statistics' },
  ]},
  { name: 'Event Platform', port: 4901, phase: 37, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'GET', path: '/api/schemas', summary: 'List schemas' },
    { method: 'POST', path: '/api/schemas', summary: 'Register schema' },
    { method: 'POST', path: '/api/events', summary: 'Publish event' },
    { method: 'GET', path: '/api/events', summary: 'Query events' },
    { method: 'GET', path: '/api/subscriptions', summary: 'List subscriptions' },
    { method: 'POST', path: '/api/subscriptions', summary: 'Subscribe' },
    { method: 'GET', path: '/api/rules', summary: 'List routing rules' },
    { method: 'POST', path: '/api/rules', summary: 'Create rule' },
    { method: 'POST', path: '/api/replay', summary: 'Replay events' },
    { method: 'GET', path: '/api/analytics', summary: 'Event analytics' },
  ]},
  { name: 'Workflow Registry', port: 4902, phase: 34, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'GET', path: '/api/templates', summary: 'List templates' },
    { method: 'POST', path: '/api/templates', summary: 'Create template' },
    { method: 'GET', path: '/api/templates/:id', summary: 'Get template' },
    { method: 'PUT', path: '/api/templates/:id', summary: 'Update template' },
    { method: 'DELETE', path: '/api/templates/:id', summary: 'Delete template' },
    { method: 'POST', path: '/api/templates/:id/versions', summary: 'Create version' },
    { method: 'GET', path: '/api/categories', summary: 'List categories' },
    { method: 'POST', path: '/api/categories', summary: 'Create category' },
    { method: 'GET', path: '/api/search', summary: 'Search templates' },
    { method: 'GET', path: '/api/analytics', summary: 'Analytics' },
  ]},
  { name: 'Twin Registry', port: 4903, phase: 35, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'GET', path: '/api/types', summary: 'List twin types' },
    { method: 'POST', path: '/api/types', summary: 'Create twin type' },
    { method: 'GET', path: '/api/instances', summary: 'List instances' },
    { method: 'POST', path: '/api/instances', summary: 'Create instance' },
    { method: 'GET', path: '/api/instances/:id', summary: 'Get instance' },
    { method: 'PUT', path: '/api/instances/:id', summary: 'Update instance' },
    { method: 'POST', path: '/api/instances/:id/relationships', summary: 'Add relationship' },
    { method: 'GET', path: '/api/stats', summary: 'Statistics' },
  ]},
  { name: 'Tenant Isolation', port: 4904, phase: 24, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'GET', path: '/api/regions', summary: 'List regions' },
    { method: 'POST', path: '/api/regions', summary: 'Create region' },
    { method: 'GET', path: '/api/assignments', summary: 'List assignments' },
    { method: 'POST', path: '/api/assignments', summary: 'Assign tenant' },
    { method: 'POST', path: '/api/failover/:tenantId', summary: 'Trigger failover' },
    { method: 'GET', path: '/api/failover/status/:tenantId', summary: 'Failover status' },
    { method: 'GET', path: '/api/routing/closest/:tenantId', summary: 'Closest region' },
    { method: 'GET', path: '/api/compliance/:tenantId', summary: 'Compliance check' },
    { method: 'GET', path: '/api/stats', summary: 'Statistics' },
  ]},
  { name: 'Fine-Tuning', port: 4610, phase: 30, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'GET', path: '/api/datasets', summary: 'List datasets' },
    { method: 'POST', path: '/api/datasets', summary: 'Create dataset' },
    { method: 'POST', path: '/api/datasets/:id/prepare', summary: 'Prepare dataset' },
    { method: 'GET', path: '/api/jobs', summary: 'List training jobs' },
    { method: 'POST', path: '/api/jobs', summary: 'Create job' },
    { method: 'POST', path: '/api/jobs/:id/start', summary: 'Start training' },
    { method: 'POST', path: '/api/jobs/:id/cancel', summary: 'Cancel job' },
    { method: 'GET', path: '/api/models', summary: 'List models' },
    { method: 'POST', path: '/api/models/:id/deploy', summary: 'Deploy model' },
  ]},
  { name: 'Eval Continuous', port: 4888, phase: 31, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'GET', path: '/api/runs', summary: 'List eval runs' },
    { method: 'POST', path: '/api/runs', summary: 'Create run' },
    { method: 'POST', path: '/api/runs/:id/trigger', summary: 'Trigger run' },
    { method: 'GET', path: '/api/metrics', summary: 'Get metrics' },
    { method: 'GET', path: '/api/metrics/trend', summary: 'Metrics trend' },
    { method: 'GET', path: '/api/baseline/:service', summary: 'Get baseline' },
    { method: 'POST', path: '/api/baseline/:service', summary: 'Set baseline' },
    { method: 'GET', path: '/api/gates/:service', summary: 'List quality gates' },
    { method: 'POST', path: '/api/gates', summary: 'Create gate' },
  ]},
  { name: 'AI Studio', port: 4890, phase: 38, routes: [
    { method: 'GET', path: '/health', summary: 'Health check' },
    { method: 'GET', path: '/api/workflows', summary: 'List workflows' },
    { method: 'POST', path: '/api/workflows', summary: 'Create workflow' },
    { method: 'GET', path: '/api/workflows/:id', summary: 'Get workflow' },
    { method: 'PUT', path: '/api/workflows/:id', summary: 'Update workflow' },
    { method: 'DELETE', path: '/api/workflows/:id', summary: 'Delete workflow' },
    { method: 'POST', path: '/api/workflows/:id/execute', summary: 'Execute workflow' },
    { method: 'GET', path: '/api/executions/:id', summary: 'Get execution' },
    { method: 'POST', path: '/api/workflows/:id/export', summary: 'Export workflow' },
    { method: 'POST', path: '/api/workflows/import', summary: 'Import workflow' },
  ]},
];

const openapi = {
  openapi: '3.0.0',
  info: {
    title: 'HOJAI AI Platform API',
    version: '5.15.0',
    description: 'All 15 HOJAI AI platform services — Agent OS, Personalization, AI Economy, Governance, Planning Engine, Multi-Modal, AIOps, Memory Lifecycle, Knowledge Registry, Event Platform, Workflow Registry, Twin Registry, Tenant Isolation, Fine-Tuning, Eval Continuous, AI Studio',
    contact: { name: 'HOJAI AI' },
  },
  servers: services.map(s => ({ url: `http://localhost:${s.port}`, description: s.name })),
  paths: {},
};

for (const svc of services) {
  for (const route of svc.routes) {
    const path = route.path.replace(/:(\w+)/g, '{$1}');
    if (!openapi.paths[path]) openapi.paths[path] = {};
    openapi.paths[path][route.method.toLowerCase()] = {
      summary: route.summary,
      tags: [svc.name],
      responses: { '200': { description: 'Success' }, '400': { description: 'Bad request' }, '404': { description: 'Not found' } },
    };
  }
}

fs.writeFileSync('openapi.json', JSON.stringify(openapi, null, 2));
console.log('Generated openapi.json with', services.length, 'services and', services.reduce((a, s) => a + s.routes.length, 0), 'routes');
