import { Server } from '@modelcontextprotocol/sdk/server/stdio.js';
import { CallToolRequestSchema, ListToolsRequestSchema } from '@modelcontextprotocol/sdk/types.js';
import express from 'express';
import { v4 as uuidv4 } from 'uuid';

const PORT = parseInt(process.env.PORT || '3133');
const app = express();
app.use(express.json());

interface Exhibit {
  id: string;
  description: string;
  evidenceId: string;
  hash?: string;
  pageRef?: string;
}

interface Report {
  id: string;
  caseId: string;
  type: 'forensic' | 'financial' | 'technical' | 'general';
  title: string;
  findings: string[];
  exhibits: Exhibit[];
  timeline?: any[];
  declaration?: string;
  expertName?: string;
  expertCredentials?: string;
  createdAt: Date;
  status: 'draft' | 'final' | 'verified';
}

const reports = new Map<string, Report>();

// Generate findings summary
app.post('/findings', (req, res) => {
  try {
    const { caseId, findings } = req.body;
    if (!findings) return res.status(400).json({ error: 'findings required' });

    const reportId = uuidv4();
    const report: Report = {
      id: reportId,
      caseId: caseId || '',
      type: 'general',
      title: `Expert Findings Report`,
      findings: findings,
      exhibits: [],
      createdAt: new Date(),
      status: 'draft'
    };

    reports.set(reportId, report);
    res.json({ success: true, reportId, findingCount: findings.length });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// Add exhibit
app.post('/report/:id/exhibit', (req, res) => {
  try {
    const report = reports.get(req.params.id);
    if (!report) return res.status(404).json({ error: 'Report not found' });

    const { description, evidenceId, hash, pageRef } = req.body;
    const exhibit: Exhibit = {
      id: uuidv4(),
      description: description || '',
      evidenceId: evidenceId || '',
      hash,
      pageRef
    };

    report.exhibits.push(exhibit);
    reports.set(report.id, report);
    res.json({ success: true, exhibitId: exhibit.id });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// Generate timeline
app.post('/report/:id/timeline', (req, res) => {
  try {
    const report = reports.get(req.params.id);
    if (!report) return res.status(404).json({ error: 'Report not found' });

    const { events } = req.body;
    if (!events) return res.status(400).json({ error: 'events required' });

    report.timeline = events.sort((a: any, b: any) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());
    reports.set(report.id, report);
    res.json({ success: true, eventCount: events.length });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// Add expert declaration
app.post('/report/:id/declaration', (req, res) => {
  try {
    const report = reports.get(req.params.id);
    if (!report) return res.status(404).json({ error: 'Report not found' });

    const { declaration, expertName, expertCredentials } = req.body;
    report.declaration = declaration || 'I declare that the information provided is true and accurate to the best of my knowledge.';
    report.expertName = expertName;
    report.expertCredentials = expertCredentials;
    reports.set(report.id, report);

    res.json({ success: true });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// Export as PDF (mock - in production use PDF library)
app.get('/report/:id/export', (req, res) => {
  const report = reports.get(req.params.id);
  if (!report) return res.status(404).json({ error: 'Report not found' });

  const htmlReport = `
<!DOCTYPE html>
<html>
<head><title>Expert Report - ${report.caseId}</title></head>
<body>
<h1>EXPERT WITNESS REPORT</h1>
<h2>Case: ${report.caseId}</h2>
<p><strong>Date:</strong> ${new Date(report.createdAt).toLocaleDateString()}</p>
<p><strong>Expert:</strong> ${report.expertName || 'Anonymous'}</p>
<p><strong>Credentials:</strong> ${report.expertCredentials || 'N/A'}</p>

<h3>Findings</h3>
<ol>
${report.findings.map((f: string) => `<li>${f}</li>`).join('\n')}
</ol>

<h3>Exhibits</h3>
<table border="1">
<tr><th>ID</th><th>Description</th><th>Evidence ID</th><th>Hash</th></tr>
${report.exhibits.map((e: Exhibit) => `<tr><td>${e.id}</td><td>${e.description}</td><td>${e.evidenceId}</td><td>${e.hash || 'N/A'}</td></tr>`).join('\n')}
</table>

<h3>Declaration</h3>
<p>${report.declaration || ''}</p>
<p><em>Signed: ${report.expertName || ''}</em></p>

<footer>
<p style="margin-top:50px">Generated by RTMZ Expert Reports System</p>
</footer>
</body>
</html>`;

  res.json({ success: true, format: 'html', content: htmlReport, note: 'Use PDF library for production PDF export' });
});

// Get report
app.get('/report/:id', (req, res) => {
  const report = reports.get(req.params.id);
  if (!report) return res.status(404).json({ error: 'Report not found' });
  res.json(report);
});

// List reports
app.get('/reports', (req, res) => {
  const all = Array.from(reports.values());
  res.json({ count: all.length, reports: all });
});

app.get('/health', (req, res) => {
  res.json({ status: 'healthy', reportCount: reports.size });
});

// MCP Server
const server = new Server({ name: 'rez-mcp-expert-reports', version: '1.0.0' }, { capabilities: { tools: {} } });

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    { name: 'generate_findings', description: 'Create findings summary', inputSchema: { type: 'object', properties: { caseId: { type: 'string' }, findings: { type: 'array', items: { type: 'string' } } } } },
    { name: 'generate_timeline', description: 'Create event timeline', inputSchema: { type: 'object', properties: { reportId: { type: 'string' }, events: { type: 'array' } } } },
    { name: 'generate_exhibit_list', description: 'Generate exhibit list', inputSchema: { type: 'object', properties: { reportId: { type: 'string' }, exhibits: { type: 'array' } } } },
    { name: 'export_pdf', description: 'Export report as PDF', inputSchema: { type: 'object', properties: { reportId: { type: 'string' } } } },
    { name: 'add_declaration', description: 'Add expert declaration', inputSchema: { type: 'object', properties: { reportId: { type: 'string' }, declaration: { type: 'string' }, expertName: { type: 'string' }, expertCredentials: { type: 'string' } } } }
  ]
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;
  try {
    switch (name) {
      case 'generate_findings':
        return { content: [{ type: 'text', text: JSON.stringify({ success: true, message: 'Use HTTP POST /findings' }) }] };
      case 'generate_timeline':
        return { content: [{ type: 'text', text: JSON.stringify({ success: true, message: 'Use HTTP POST /report/{id}/timeline' }) }] };
      case 'generate_exhibit_list':
        return { content: [{ type: 'text', text: JSON.stringify({ success: true, exhibits: args?.exhibits || [] }) }] };
      case 'export_pdf':
        return { content: [{ type: 'text', text: JSON.stringify({ success: true, message: 'Use HTTP GET /report/{id}/export' }) }] };
      case 'add_declaration':
        return { content: [{ type: 'text', text: JSON.stringify({ success: true, message: 'Use HTTP POST /report/{id}/declaration' }) }] };
      default:
        return { content: [{ type: 'text', text: `Unknown tool: ${name}` }], isError: true };
    }
  } catch (error: any) {
    return { content: [{ type: 'text', text: `Error: ${error.message}` }], isError: true };
  }
});

if (process.env.TRANSPORT === 'http') {
  app.listen(PORT, () => console.log(`Expert Reports MCP on port ${PORT}`));
} else {
  server.connect();
  console.error('Expert Reports MCP running');
}