/**
 * OTA Mobile API Service
 * Generated by HOJAI Studio
 */
import axios from 'axios';

// API Configuration
const API_BASE = process.env.API_URL || 'https://api.travelmate.hojai.app';

const api = axios.create({
  baseURL: API_BASE,
  timeout: 30000,
  headers: { 'Content-Type': 'application/json' },
});

// ── Hotels ────────────────────────────────────────────────────────────

export const searchHotels = async (params: {
  city?: string;
  checkin?: string;
  checkout?: string;
  guests?: number;
  minPrice?: number;
  maxPrice?: number;
  rating?: number;
}) => {
  const res = await api.get('/api/hotels', { params });
  return res.data;
};

export const getHotelDetail = async (hotelId: string) => {
  const res = await api.get(`/api/hotels/${hotelId}`);
  return res.data;
};

export const bookHotel = async (booking: {
  hotelId: string;
  checkin: string;
  checkout: string;
  guests: number;
  roomType: string;
  paymentMethod: string;
}) => {
  const res = await api.post('/api/hotels/book', booking);
  return res.data;
};

// ── Flights ──────────────────────────────────────────────────────────

export const searchFlights = async (params: {
  from?: string;
  to?: string;
  date?: string;
  returnDate?: string;
  class?: 'economy' | 'business' | 'first';
  passengers?: number;
}) => {
  const res = await api.get('/api/flights', { params });
  return res.data;
};

export const bookFlight = async (booking: {
  flightId: string;
  passengers: number;
  seatSelection?: string[];
  paymentMethod: string;
}) => {
  const res = await api.post('/api/flights/book', booking);
  return res.data;
};

// ── Packages ─────────────────────────────────────────────────────────

export const searchPackages = async (params: {
  destination?: string;
  nights?: number;
  travelers?: number;
  budget?: number;
}) => {
  const res = await api.get('/api/packages', { params });
  return res.data;
};

export const bookPackage = async (booking: {
  packageId: string;
  travelers: number;
  date: string;
  paymentMethod: string;
}) => {
  const res = await api.post('/api/packages/book', booking);
  return res.data;
};

// ── AI Trip Planner ─────────────────────────────────────────────────

export const planTrip = async (params: {
  destination: string;
  dates: { start: string; end: string };
  budget: number;
  travelers: number;
  preferences?: string[];
}) => {
  const res = await api.post('/api/trip/plan', params);
  return res.data;
};

// ── Bookings ──────────────────────────────────────────────────────────

export const getBookings = async () => {
  const res = await api.get('/api/bookings');
  return res.data;
};

export const getBookingDetail = async (bookingId: string) => {
  const res = await api.get(`/api/bookings/${bookingId}`);
  return res.data;
};

export const cancelBooking = async (bookingId: string, reason?: string) => {
  const res = await api.post(`/api/bookings/${bookingId}/cancel`, { reason });
  return res.data;
};

// ── Payments ─────────────────────────────────────────────────────────

export const initiatePayment = async (params: {
  bookingId: string;
  method: 'upi' | 'card' | 'wallet' | 'netbanking';
}) => {
  const res = await api.post('/api/payment/initiate', params);
  return res.data;
};

export const verifyPayment = async (transactionId: string) => {
  const res = await api.post('/api/payment/verify', { transactionId });
  return res.data;
};

// ── Corporate ─────────────────────────────────────────────────────────

export const corporateBook = async (booking: {
  employeeId: string;
  type: 'hotel' | 'flight' | 'package';
  details: any;
  policyApproval?: boolean;
}) => {
  const res = await api.post('/api/corporate/book', booking);
  return res.data;
};

// ── User ─────────────────────────────────────────────────────────────

export const getUserProfile = async () => {
  const res = await api.get('/api/user/profile');
  return res.data;
};

export const updateUserProfile = async (data: any) => {
  const res = await api.put('/api/user/profile', data);
  return res.data;
};

export default api;
