/**
 * Morning Briefing v2
 *
 * Port: 4794
 *
 * The daily engagement hook. Every morning, this composes:
 *   1. Today's calendar (from genie-calendar-service)
 *   2. Active goals (from memory-substrate / genie-goal-os)
 *   3. Relationship reminders (from genie-relationship-os)
 *   4. Wellness check-in (from genie-wellness-os)
 *   5. A personal note generated by LLM that ties it all together
 *
 * Then it returns ONE warm, scannable message — not 5 separate API calls.
 *
 * Why this is the v2 (not the existing genie-briefing-service):
 *   - genie-briefing-service is a static specialist with hard-coded sections
 *   - v2 is LLM-composed, context-aware, reads the user's full memory substrate
 *   - v2 handles graceful degradation (any one specialist being down = show what works)
 *
 * Engagement loop:
 *   - Cron-like job hits POST /api/briefing/morning at 7am user-local
 *   - User gets a push notification with the message
 *   - User can tap "tell me more" on any section → deeper LLM response
 *
 * Routes:
 *   POST /api/briefing/morning          — Generate today's morning briefing
 *   POST /api/briefing/morning/expand   — Expand a section on demand
 *   GET  /api/briefing/history/:userId  — Last 7 days of briefings
 *   GET  /health
 *   GET  /ready
 */

import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import crypto from 'node:crypto';
import { requireAuth } from '@rtmn/shared/auth';
import { requireEnv } from '@rtmn/shared/lib/env';
import { installGracefulShutdown } from '@rtmn/shared/lib/shutdown';
import { PersistentMap } from '@rtmn/shared/lib/persistent-map';
import { createLogger } from '@rtmn/shared/lib/logger';
import { createLLMClient } from '@rtmn/shared/lib/llm';

const PORT = parseInt(process.env.PORT || '4794', 10);
const MEMORY_SUBSTRATE_URL = process.env.MEMORY_SUBSTRATE_URL || 'http://localhost:4791';
const GENIE_CALENDAR_URL = process.env.GENIE_CALENDAR_URL || 'http://localhost:4709';
const GENIE_RELATIONSHIP_URL = process.env.GENIE_RELATIONSHIP_URL || 'http://localhost:4747';
const GENIE_WELLNESS_URL = process.env.GENIE_WELLNESS_URL || 'http://localhost:4723';
const GENIE_GOAL_URL = process.env.GENIE_GOAL_URL || 'http://localhost:4763';
// Phase 3 — Personal Intelligence OS
const PI_SCORE_URL = process.env.PI_SCORE_URL || 'http://localhost:4798';
const RELATIONSHIP_GRAPH_URL = process.env.RELATIONSHIP_GRAPH_URL || 'http://localhost:4799';
const LEARNING_OS_V2_URL = process.env.LEARNING_OS_V2_URL || 'http://localhost:4800';
const REFLECTION_ENGINE_URL = process.env.REFLECTION_ENGINE_URL || 'http://localhost:4796';
const PROACTIVE_ENGINE_URL = process.env.PROACTIVE_ENGINE_URL || 'http://localhost:4797';
const INTERNAL_TOKEN = process.env.INTERNAL_SERVICE_TOKEN || '';

const log = createLogger('morning-briefing-v2');

const history = new PersistentMap('briefing-history', { serviceName: 'morning-briefing-v2' });

const app = express();
app.use(helmet()); app.use(cors()); app.use(express.json({ limit: '1mb' }));
app.use(morgan('tiny'));

const send = (res, s, d) => res.status(s).json({ success: true, data: d, meta: { timestamp: new Date().toISOString() } });
const sendErr = (res, s, code, msg) => res.status(s).json({ success: false, error: { code, message: msg }, meta: { timestamp: new Date().toISOString() } });

// === Helper: call downstream service (best-effort, never throws) ===
async function tryFetch(url, options = {}) {
  try {
    const ctrl = new AbortController();
    const t = setTimeout(() => ctrl.abort(), 3000);
    const res = await fetch(url, { ...options, signal: ctrl.signal });
    clearTimeout(t);
    if (!res.ok) return null;
    return await res.json();
  } catch (e) {
    log.warn(`downstream ${url} unavailable:`, e.message);
    return null;
  }
}

function internalHeaders(extra = {}) {
  return { 'content-type': 'application/json', 'x-internal-token': INTERNAL_TOKEN, ...extra };
}

// === HEALTH ===
app.get('/health', (req, res) => send(res, 200, {
  status: 'healthy',
  service: 'morning-briefing-v2',
  port: PORT,
  version: '2.0.0',
  sources: {
    memory_substrate: MEMORY_SUBSTRATE_URL,
    calendar: GENIE_CALENDAR_URL,
    relationships: GENIE_RELATIONSHIP_URL,
    wellness: GENIE_WELLNESS_URL,
    pi_score: PI_SCORE_URL,
    relationship_graph: RELATIONSHIP_GRAPH_URL,
    learning_os_v2: LEARNING_OS_V2_URL,
    reflection_engine: REFLECTION_ENGINE_URL,
    proactive_engine: PROACTIVE_ENGINE_URL,
  },
}));
app.get('/ready', (req, res) => send(res, 200, { ready: true }));

// === MORNING BRIEFING ===
app.post('/api/briefing/morning', requireAuth, async (req, res) => {
  const { userId } = req.body;
  if (!userId) return sendErr(res, 400, 'VALIDATION', 'userId required');

  const today = new Date().toISOString().slice(0, 10);

  // Fan out to all data sources in parallel — any one being down doesn't kill the briefing
  // Phase 1/2 sources + Phase 3 (PI Score, relationship-graph, learning-os-v2, reflection, proactive)
  const [calendar, relationships, wellness, memoryCtx, goals, piScore, relGraph, learningDue, reflection, proactive] = await Promise.all([
    tryFetch(`${GENIE_CALENDAR_URL}/api/events/today?userId=${userId}`, { headers: internalHeaders() }),
    tryFetch(`${GENIE_RELATIONSHIP_URL}/api/relationships/due?userId=${userId}`, { headers: internalHeaders() }),
    tryFetch(`${GENIE_WELLNESS_URL}/api/wellness/today?userId=${userId}`, { headers: internalHeaders() }),
    tryFetch(`${MEMORY_SUBSTRATE_URL}/api/context/${userId}?query=briefing&limit=10`, { headers: internalHeaders() }),
    tryFetch(`${GENIE_GOAL_URL}/api/goals/${userId}?status=active`, { headers: internalHeaders() }),
    tryFetch(`${PI_SCORE_URL}/api/pi-score/${userId}/widget`, { headers: internalHeaders() }),
    tryFetch(`${RELATIONSHIP_GRAPH_URL}/api/relationships/${userId}/stale?minStrength=30&minDays=7&limit=5`, { headers: internalHeaders() }),
    tryFetch(`${LEARNING_OS_V2_URL}/api/learning/due/${userId}?threshold=0.7&limit=5`, { headers: internalHeaders() }),
    tryFetch(`${REFLECTION_ENGINE_URL}/api/reflection/${userId}`, { headers: internalHeaders() }),
    tryFetch(`${PROACTIVE_ENGINE_URL}/api/proactive/check`, { method: 'POST', headers: internalHeaders(), body: JSON.stringify({ userId }) }),
  ]);

  // Build structured sections
  const sections = {
    calendar: {
      available: !!calendar,
      events: calendar?.data?.events || calendar?.events || [],
      summary: `${(calendar?.data?.events || calendar?.events || []).length} events today`,
    },
    relationships: {
      available: !!relationships,
      dueOutreach: relationships?.data?.due || relationships?.due || [],
      summary: `${(relationships?.data?.due || relationships?.due || []).length} people to reach out to`,
    },
    wellness: {
      available: !!wellness,
      snapshot: wellness?.data || wellness || null,
      summary: wellness ? 'Wellness check-in available' : 'Wellness offline',
    },
    goals: {
      available: !!goals,
      active: goals?.data?.items || goals?.items || [],
      summary: `${(goals?.data?.items || goals?.items || []).length} active goals`,
    },
    memory: {
      available: !!memoryCtx,
      recentFacts: memoryCtx?.data?.facts || memoryCtx?.facts || [],
    },
    // Phase 3 sections
    piScore: {
      available: !!piScore,
      widget: piScore?.data || null,
      summary: piScore?.data
        ? `${piScore.data.levelEmoji || ''} Genie is a ${piScore.data.levelName} (${piScore.data.overall}/100)`
        : 'PI Score offline',
    },
    relationshipGraph: {
      available: !!relGraph,
      stale: relGraph?.data?.candidates || [],
      summary: relGraph?.data
        ? `${(relGraph.data.candidates || []).length} relationships could use attention`
        : 'Relationship graph offline',
    },
    learning: {
      available: !!learningDue,
      due: learningDue?.data?.due || [],
      summary: learningDue?.data
        ? `${(learningDue.data.due || []).length} facts to refresh`
        : 'Learning OS offline',
    },
    reflection: {
      available: !!reflection,
      latest: reflection?.data || null,
      summary: reflection?.data
        ? `Last reflection: ${reflection.data.summary?.slice(0, 80) || ''}`
        : 'No reflection yet',
    },
    proactive: {
      available: !!proactive,
      suggestions: proactive?.data?.suggestions || proactive?.suggestions || [],
      summary: proactive?.data?.suggestions?.length
        ? `${proactive.data.suggestions.length} proactive suggestions`
        : 'No proactive nudges',
    },
  };

  // Generate the personal note via LLM
  let personalNote = 'Have a great day!';
  let greeting = 'Good morning!';
  try {
    const llm = createLLMClient({ provider: process.env.LLM_PROVIDER || 'anthropic' });

    const userName = sections.memory.recentFacts.find(f => /name is|i am|i'm called/i.test(f.content))?.content || 'friend';
    const today_events = sections.calendar.events.map(e => e.title || e.summary).filter(Boolean).slice(0, 3);
    const goal_titles = sections.goals.active.map(g => g.title || g.name).filter(Boolean).slice(0, 2);
    const people = sections.relationships.dueOutreach.map(r => r.name).filter(Boolean).slice(0, 2);
    const piLine = sections.piScore.available
      ? `Your Genie is a ${sections.piScore.widget.levelName} (${sections.piScore.widget.overall}/100)`
      : '';
    const duePeople = sections.relationshipGraph.stale.slice(0, 2).map(r => r.name).filter(Boolean);
    const dueFacts = sections.learning.due.slice(0, 2).map(f => f.text).filter(Boolean);

    const prompt = `Write a warm, brief morning greeting for ${userName}. Today is ${today}.

What I know about their day:
- Calendar: ${today_events.length ? today_events.join(', ') : 'clear'}
- Active goals: ${goal_titles.length ? goal_titles.join(', ') : 'none set'}
- People to reach out to: ${people.length ? people.join(', ') : 'no one flagged'}
- Wellness: ${sections.wellness.available ? 'tracked' : 'not tracked'}
${piLine ? `- ${piLine}` : ''}
${duePeople.length ? `- Stale relationships: ${duePeople.join(', ')}` : ''}
${dueFacts.length ? `- Facts due for refresh: ${dueFacts.join('; ')}` : ''}

Write 2-3 sentences. Be warm but not saccharine. Use a casual tone unless otherwise noted. Don't be a generic assistant. Reference something specific if available.`;

    const result = await llm.complete({
      messages: [{ role: 'user', content: prompt }],
      maxTokens: 200,
    });
    personalNote = result.text.trim();
    greeting = personalNote.split(/[.!?]/)[0] + (personalNote.match(/[.!?]/) || ['!'])[0];
  } catch (e) {
    log.warn('LLM unavailable for personal note, using template', { error: e.message });
    personalNote = `Good morning! You have ${sections.calendar.events.length} events today and ${sections.goals.active.length} active goals. Let's make it count.`;
    greeting = 'Good morning!';
  }

  // Compose the final message
  const message = [
    greeting,
    '',
    personalNote,
    '',
    `📅 ${sections.calendar.summary}`,
    `🎯 ${sections.goals.summary}`,
    `💌 ${sections.relationships.summary}`,
    sections.piScore.available ? `🌱 ${sections.piScore.summary}` : null,
    sections.learning.due.length ? `🧠 ${sections.learning.summary}` : null,
  ].filter(Boolean).join('\n');

  // Save to history
  const briefingId = `brf_${crypto.randomBytes(6).toString('hex')}`;
  const briefing = {
    id: briefingId,
    userId,
    date: today,
    generatedAt: new Date().toISOString(),
    greeting,
    personalNote,
    sections,
    message,
  };
  history.set(`${userId}:${today}`, briefing);

  send(res, 200, briefing);
});

// === EXPAND A SECTION ===
app.post('/api/briefing/morning/expand', requireAuth, async (req, res) => {
  const { userId, section, briefingId } = req.body;
  if (!userId || !section) return sendErr(res, 400, 'VALIDATION', 'userId and section required');

  // Look up the briefing
  const today = new Date().toISOString().slice(0, 10);
  const briefing = history.get(`${userId}:${today}`) || history.get(briefingId);

  if (!briefing) return sendErr(res, 404, 'NOT_FOUND', 'No briefing found for today — generate one first');

  const sectionData = briefing.sections[section];
  if (!sectionData) return sendErr(res, 400, 'VALIDATION', `Unknown section: ${section}`);

  let expansion = '';
  try {
    const llm = createLLMClient({ provider: process.env.LLM_PROVIDER || 'anthropic' });
    const prompt = `Expand on the "${section}" section of today's briefing. Be specific and helpful. The data: ${JSON.stringify(sectionData).slice(0, 1500)}`;
    const result = await llm.complete({ messages: [{ role: 'user', content: prompt }], maxTokens: 400 });
    expansion = result.text.trim();
  } catch (e) {
    expansion = `${section} details: ${JSON.stringify(sectionData, null, 2).slice(0, 800)}`;
  }

  send(res, 200, {
    section,
    expansion,
    raw: sectionData,
  });
});

// === HISTORY ===
app.get('/api/briefing/history/:userId', requireAuth, (req, res) => {
  const { userId } = req.params;
  const today = new Date();
  const items = [];

  for (let i = 0; i < 7; i++) {
    const d = new Date(today);
    d.setDate(d.getDate() - i);
    const key = `${userId}:${d.toISOString().slice(0, 10)}`;
    const b = history.get(key);
    if (b) items.push({ date: b.date, id: b.id, greeting: b.greeting, message: b.message });
  }

  send(res, 200, { userId, count: items.length, briefings: items });
});

requireEnv(['PORT'], { allowDev: true });

const server = app.listen(PORT, () => {
  log.info(`morning-briefing-v2 listening on :${PORT}`);
});

installGracefulShutdown(server, 'morning-briefing-v2');

export default app;
