/**
 * hojai.ai.md templates — one per starter type + a generic + an SDK variant.
 *
 * The rendered file is the primary thing AI coding tools read. It must
 * be informative, scannable, and accurate. Templates take the manifest
 * and capability as inputs and produce the markdown.
 */

import type { Manifest, Capability, StarterType } from './types.js';

export interface RenderInput {
  manifest: Manifest;
  capability: Capability;
}

const TEMPLATE_HEADER = `# HOJAI Project: {{NAME}}

> This file is auto-generated by HOJAI Foundry / @hojai/ai-spec.
> AI coding assistants (Claude Code, Cursor, Codex, GitHub Copilot) should read this file first to understand the project.
> Schema version: {{SCHEMA_VERSION}}

## What this app does

{{NAME}}{{DESCRIPTION_SUFFIX}}

Region: **{{REGION}}** · Languages: **{{LANGUAGES}}** · Template: **{{TYPE}}** · HOJAI version: **{{HOJAI_VERSION}}**
`;

/** Render a description clause — either " — <desc>" or empty */
function descClause(manifest: Manifest): string {
  return manifest.description ? ` — ${manifest.description}` : ' — built with HOJAI Foundry.';
}

const TEMPLATE_FOOTER = `
## How to Extend

### Add a new SUTAR agent

1. Open \`apps/backend/src/agents/index.ts\`
2. Add an entry to the \`AGENTS\` array
3. Wire the new agent's logic in the same file
4. Update \`.hojai/capability.json\` with the new capability

### Add a new endpoint

1. Create a file in \`apps/backend/src/routes/\`
2. Use the \`requireAuth\` middleware from \`@hojai/foundation\`
3. Validate inputs with Zod
4. Re-export the router from \`apps/backend/src/index.ts\`

### Connect to the Global Nexha network

POST to \`/api/nexha/peers/connect\` with your federation credentials, or run \`npx hojai connect-nexha\`.

## Conventions

- Use \`requireAuth\` middleware from \`@hojai/foundation\` on all \`/api/v1/*\` routes
- Validate inputs with Zod
- All agents must extend \`BaseAgent\` from \`@hojai/sutar\`
- All Nexha events must use \`NexhaEvent\` from \`@hojai/nexha\`

## License

MIT (HOJAI starter code) + HOJAI Cloud subscription (for production deployment).
`;

const AGENT_TABLE = (input: RenderInput) => {
  if (input.manifest.agents.length === 0) return '';
  const rows = input.manifest.agents.map(a => `| ${a.role} | ${a.purpose}${a.file ? ` | \`${a.file}\` |` : ' | |'}`).join('\n');
  return `\n## SUTAR Agents\n\n| Role | Purpose | File |\n|---|---|---|\n${rows}\n`;
};

const STACK_SECTION = (input: RenderInput) => {
  if (!input.manifest.stack) return '';
  const lines: string[] = [];
  for (const [k, v] of Object.entries(input.manifest.stack)) {
    if (v) lines.push(`- **${k}:** ${Array.isArray(v) ? v.join(', ') : v}`);
  }
  return lines.length === 0 ? '' : `\n## Architecture\n\n${lines.join('\n')}\n`;
};

const INTEGRATIONS_SECTION = (input: RenderInput) => {
  if (input.manifest.integrations.length === 0) return '';
  const lines = input.manifest.integrations.map(i => `- \`@hojai/${i}\` — ${describeIntegration(i)}`).join('\n');
  return `\n## HOJAI SDKs Used\n\n${lines}\n`;
};

function describeIntegration(name: string): string {
  const map: Record<string, string> = {
    foundation: 'CorpID, Memory, Twin, Trust, Flow, Policy',
    sutar: 'SUTAR agent runtime',
    nexha: 'Nexha federation network',
    marketplace: 'BAM marketplace',
    commerce: 'RABTUL commerce',
    payment: 'Payments + escrow + BNPL',
    logistics: 'KHAIRMOVE logistics',
    reputation: 'ACI scoring + disputes',
    discovery: 'Capability search',
    genie: 'Personal AI assistant',
    industry: '26 vertical Industry OSes',
    department: '9 horizontal Department OSes',
    memory: 'Memory Layer (5 services)',
    twin: 'TwinOS Hub + 4 specialized twins',
    skills: 'SkillOS + Prompts + Workflows',
    media: 'Media OS (streaming + content)',
    cli: 'Command-line tool'
  };
  return map[name] ?? name;
}

const CONVENTIONS_SECTION = (input: RenderInput) => {
  if (!input.manifest.conventions) return '';
  const lines: string[] = [];
  for (const [k, v] of Object.entries(input.manifest.conventions)) {
    if (v) lines.push(`- **${k}:** ${v}`);
  }
  return lines.length === 0 ? '' : `\n## Conventions\n\n${lines.join('\n')}\n`;
};

const ENTRYPOINTS_SECTION = (input: RenderInput) => {
  if (!input.manifest.entrypoints) return '';
  const lines: string[] = [];
  for (const [k, v] of Object.entries(input.manifest.entrypoints)) {
    if (v) lines.push(`- **${k}:** \`${v}\``);
  }
  return lines.length === 0 ? '' : `\n## Entry Points\n\n${lines.join('\n')}\n`;
};

const SCRIPTS_SECTION = (input: RenderInput) => {
  if (!input.manifest.scripts) return '';
  const lines: string[] = [];
  for (const [k, v] of Object.entries(input.manifest.scripts)) {
    if (v) lines.push(`- \`npm run ${k}\` — ${v}`);
  }
  return lines.length === 0 ? '' : `\n## Scripts\n\n${lines.join('\n')}\n`;
};

/** Render a starter-type-specific preamble. */
function starterPreamble(type: StarterType): string {
  const preambles: Partial<Record<StarterType, string>> = {
    marketplace: '\nThis is a **multi-vendor marketplace**. Buyers browse products, post RFQs, and receive quotes from sellers. Orders flow through payment, logistics, and reputation layers.\n',
    b2b: '\nThis is a **B2B platform**. Buyers post RFQs, sellers respond with quotes. Trade finance + escrow + multi-party contracts are built in.\n',
    company: '\nThis is a **full autonomous company**. One business, many departments (Sales, Marketing, HR, Finance, Ops) — each with its own SUTAR agents.\n',
    hotel: '\nThis is a **hotel management system**. Property + rooms + bookings + guest profiles + housekeeping + revenue management.\n',
    restaurant: '\nThis is a **restaurant OS**. Menu + tables + KOT + billing + delivery + kitchen coordination.\n',
    logistics: '\nThis is a **logistics platform**. Fleet + dispatch + last-mile delivery + tracking + rate shopping.\n',
    crm: '\nThis is a **CRM with SUTAR agents**. Lead capture, pipeline, customer 360, and AI-powered follow-up.\n',
    erp: '\nThis is an **ERP with SUTAR agents**. Procurement, inventory, GL, AP/AR, all powered by AI employees.\n',
    pos: '\nThis is a **point-of-sale system**. Counter + barcode + receipts + inventory sync.\n',
    sdk: '\nThis is a **HOJAI SDK package**. Published to npm; consumed by HOJAI applications.\n',
    library: '\nThis is a **HOJAI library package**. A reusable TypeScript helper for HOJAI applications.\n',
    other: ''
  };
  return preambles[type] ?? '';
}

/** Public templates — key by starter type */
export const TEMPLATES: Record<StarterType, (input: RenderInput) => string> = {
  marketplace: render,
  b2b: render,
  company: render,
  hotel: render,
  restaurant: render,
  logistics: render,
  crm: render,
  erp: render,
  pos: render,
  sdk: render,
  library: render,
  other: render
};

/** Main render function. */
export function render(input: RenderInput): string {
  const m = input.manifest;
  const c = input.capability;
  const languageList = m.languages.join(', ');
  // Substitute {{NAME}} globally in the header template (it appears twice).
  const header = TEMPLATE_HEADER
    .replace(/\{\{NAME\}\}/g, m.name)
    .replace('{{SCHEMA_VERSION}}', m.schemaVersion)
    .replace('{{DESCRIPTION_SUFFIX}}', descClause(m))
    .replace('{{REGION}}', m.region ?? 'global')
    .replace('{{LANGUAGES}}', languageList)
    .replace('{{TYPE}}', m.type)
    .replace('{{HOJAI_VERSION}}', m.hojaiVersion);

  const sections = [
    starterPreamble(m.type),
    STACK_SECTION(input),
    AGENT_TABLE(input),
    INTEGRATIONS_SECTION(input),
    c.capabilities.length > 0 ? `\n## Nexha Federation\n\nThis project joins the Global Nexha network with ${c.capabilities.length} capabilities.\n` : '',
    ENTRYPOINTS_SECTION(input),
    SCRIPTS_SECTION(input),
    CONVENTIONS_SECTION(input),
    TEMPLATE_FOOTER
  ];
  return header + sections.join('');
}

/** Pick the right template by starter type. Always falls back to generic. */
export function renderFor(input: RenderInput): string {
  const tmpl = TEMPLATES[input.manifest.type] ?? render;
  return tmpl(input);
}
