/**
 * E-Commerce Admin Dashboard API
 * Generated by HOJAI Studio
 *
 * Features:
 * - Full dashboard with analytics
 * - User management
 * - Content moderation
 * - Platform-wide settings
 */
import express from 'express';
import cors from 'cors';
import { v4 as uuidv4 } from 'uuid';

const app = express();
app.use(cors(), express.json());
const PORT = process.env.PORT || 3002;

// ── In-Memory Database ─────────────────────────────────────────────────────────

const users = new Map();
const orders = new Map();
const sellers = new Map();
const products = new Map();
const moderationQueue = new Map();

// Seed data
const stats = {
  totalUsers: 125000,
  totalOrders: 450000,
  totalRevenue: 1250000000,
  totalSellers: 15000,
  pendingOrders: 1234,
  disputedOrders: 56,
  activeSellers: 12340,
  newUsersToday: 1250
};

// ── Routes ─────────────────────────────────────────────────────────────────────

app.get('/health', (_, res) => res.json({ status: 'ok', app: 'ecommerce-admin' }));

// Dashboard
app.get('/api/admin/dashboard', (_, res) => {
  res.json({
    success: true,
    stats,
    trends: {
      ordersGrowth: '+18%',
      revenueGrowth: '+24%',
      usersGrowth: '+12%',
      sellerGrowth: '+8%'
    }
  });
});

app.get('/api/admin/stats', (_, res) => {
  res.json({
    success: true,
    stats,
    charts: {
      ordersByDay: [
        { day: 'Mon', orders: 4500 },
        { day: 'Tue', orders: 5200 },
        { day: 'Wed', orders: 4800 },
        { day: 'Thu', orders: 6100 },
        { day: 'Fri', orders: 7200 },
        { day: 'Sat', orders: 8500 },
        { day: 'Sun', orders: 7800 }
      ],
      topCategories: [
        { category: 'Electronics', sales: 45000000 },
        { category: 'Fashion', sales: 32000000 },
        { category: 'Home', sales: 18000000 },
        { category: 'Books', sales: 12000000 }
      ]
    }
  });
});

// Users
app.get('/api/admin/users', (req, res) => {
  const { page = 1, limit = 50, search } = req.query;
  const allUsers = Array.from(users.values());

  let filtered = allUsers;
  if (search) {
    filtered = allUsers.filter(u =>
      u.name.toLowerCase().includes(search.toLowerCase()) ||
      u.email.toLowerCase().includes(search.toLowerCase())
    );
  }

  const start = (page - 1) * limit;
  res.json({
    success: true,
    users: filtered.slice(start, start + parseInt(limit)),
    total: filtered.length
  });
});

// Sellers
app.get('/api/admin/sellers', (req, res) => {
  const { status, page = 1, limit = 50 } = req.query;
  let allSellers = Array.from(sellers.values());

  if (status) {
    allSellers = allSellers.filter(s => s.status === status);
  }

  const start = (page - 1) * limit;
  res.json({
    success: true,
    sellers: allSellers.slice(start, start + parseInt(limit)),
    total: allSellers.length
  });
});

app.put('/api/admin/sellers/:id/status', (req, res) => {
  const seller = sellers.get(req.params.id);
  if (!seller) return res.status(404).json({ error: 'Seller not found' });

  seller.status = req.body.status;
  res.json({ success: true, seller });
});

// Orders
app.get('/api/admin/orders', (req, res) => {
  const { status, page = 1, limit = 50 } = req.query;
  let allOrders = Array.from(orders.values());

  if (status) {
    allOrders = allOrders.filter(o => o.status === status);
  }

  const start = (page - 1) * limit;
  res.json({
    success: true,
    orders: allOrders.slice(start, start + parseInt(limit)),
    total: allOrders.length
  });
});

app.put('/api/admin/orders/:id/status', (req, res) => {
  const order = orders.get(req.params.id);
  if (!order) return res.status(404).json({ error: 'Order not found' });

  order.status = req.body.status;
  res.json({ success: true, order });
});

// Moderation
app.get('/api/admin/moderation', (req, res) => {
  const queue = Array.from(moderationQueue.values());
  res.json({ success: true, queue, count: queue.length });
});

app.post('/api/admin/moderation/:id/approve', (req, res) => {
  moderationQueue.delete(req.params.id);
  res.json({ success: true });
});

app.post('/api/admin/moderation/:id/reject', (req, res) => {
  const item = moderationQueue.get(req.params.id);
  if (item) {
    item.rejected = true;
    item.reason = req.body.reason;
  }
  moderationQueue.delete(req.params.id);
  res.json({ success: true });
});

// Analytics
app.get('/api/admin/analytics/sales', (req, res) => {
  res.json({
    success: true,
    data: {
      totalSales: stats.totalRevenue,
      ordersCount: stats.totalOrders,
      averageOrderValue: Math.round(stats.totalRevenue / stats.totalOrders),
      conversionRate: 3.2
    }
  });
});

app.listen(PORT, () => {
  console.log(`
╔══════════════════════════════════════════════════════════════╗
║  📊  E-Commerce Admin Dashboard — PORT ${PORT}              ║
║  Full platform control & analytics                      ║
╚══════════════════════════════════════════════════════════════╝
  `);
});

export default app;
