/**
 * RTMN Unified Hub — Service Registry
 *
 * Single entry point for all RTMN services.
 * Routes /api/* to appropriate downstream services.
 * Provides service health monitoring.
 */

export interface ServiceEntry {
  name: string;
  url: string;
  prefix: string;            // URL prefix to route
  healthPath: string;        // health check path
  timeout: number;
  category: 'genie' | 'rtmn' | 'integration' | 'rabtul';
  /**
   * If true (default), strip the matched prefix from the path before forwarding.
   * Set to false for services that register routes with the full /api/<prefix> baked in.
   * Currently: Template Engine, Vendor Pools, Product Graph, Universal Distribution,
   * Commerce Studio use stripPrefix=false.
   * Trade Finance and Cross Border use the default (true) — they register routes
   * without the /api/<prefix> prefix.
   */
  stripPrefix?: boolean;
}

export const SERVICE_REGISTRY: ServiceEntry[] = [
  // ====== Genie OS Runtime (port 7100) ======
  // Genie has its own router that includes all 14 sub-services
  {
    name: 'Genie Runtime',
    url: process.env.GENIE_RUNTIME_URL || 'http://localhost:7100',
    prefix: '/api/genie',
    healthPath: '/health',
    timeout: 10000,
    category: 'genie',
  },
  {
    name: 'Genie Twinst (Wish Service)',
    url: process.env.GENIE_TWINS_URL || 'http://localhost:4001',
    prefix: '/api/genie-twins',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Genie Agents (Wish Service)',
    url: process.env.GENIE_AGENTS_URL || 'http://localhost:4001',
    prefix: '/api/genie-agents',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },

  // ====== Direct access to 14 Genie services ======
  {
    name: 'Decision Intelligence',
    url: process.env.DECISION_INTELLIGENCE_URL || 'http://localhost:4740',
    prefix: '/api/services/decision',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Learning Loop',
    url: process.env.LEARNING_LOOP_URL || 'http://localhost:4742',
    prefix: '/api/services/learning',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Anticipation',
    url: process.env.ANTICIPATION_URL || 'http://localhost:4745',
    prefix: '/api/services/anticipation',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Ambient',
    url: process.env.AMBIENT_URL || 'http://localhost:4746',
    prefix: '/api/services/ambient',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Constitution',
    url: process.env.CONSTITUTION_URL || 'http://localhost:4743',
    prefix: '/api/services/constitution',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Financial Life',
    url: process.env.FINANCIAL_LIFE_URL || 'http://localhost:4747',
    prefix: '/api/services/financial',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Health Intelligence',
    url: process.env.HEALTH_URL || 'http://localhost:4748',
    prefix: '/api/services/health',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Household',
    url: process.env.HOUSEHOLD_URL || 'http://localhost:4749',
    prefix: '/api/services/household',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Travel',
    url: process.env.TRAVEL_URL || 'http://localhost:4750',
    prefix: '/api/services/travel',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Spiritual',
    url: process.env.SPIRITUAL_URL || 'http://localhost:4751',
    prefix: '/api/services/spiritual',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Life Simulation',
    url: process.env.LIFE_SIMULATION_URL || 'http://localhost:4752',
    prefix: '/api/services/simulation',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Focus',
    url: process.env.FOCUS_URL || 'http://localhost:4753',
    prefix: '/api/services/focus',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Dreams',
    url: process.env.DREAMS_URL || 'http://localhost:4754',
    prefix: '/api/services/dreams',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Legacy',
    url: process.env.LEGACY_URL || 'http://localhost:4755',
    prefix: '/api/services/legacy',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },

  // ====== Other RTMN Services ======
  {
    name: 'Genie Gateway',
    url: process.env.GENIE_GATEWAY_URL || 'http://localhost:4701',
    prefix: '/api/genie-gateway',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Genie Wish Fulfillment',
    url: process.env.GENIE_WISHES_URL || 'http://localhost:4001',
    prefix: '/api/wishes',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Genie Fulfillments',
    url: process.env.GENIE_WISHES_URL || 'http://localhost:4001',
    prefix: '/api/fulfillments',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Genie Templates',
    url: process.env.GENIE_WISHES_URL || 'http://localhost:4001',
    prefix: '/api/genie-templates',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Genie Skills',
    url: process.env.GENIE_WISHES_URL || 'http://localhost:4001',
    prefix: '/api/skills',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'MemoryOS',
    url: process.env.MEMORYOS_URL || 'http://localhost:4703',
    prefix: '/api/memory',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'TwinOS',
    url: process.env.TWINOS_URL || 'http://localhost:4705',
    prefix: '/api/twin',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'CorpID',
    url: process.env.CORPID_URL || 'http://localhost:4702',
    prefix: '/api/corpid',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Calendar',
    url: process.env.CALENDAR_URL || 'http://localhost:4709',
    prefix: '/api/calendar',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Wellness',
    url: process.env.WELLNESS_URL || 'http://localhost:4723',
    prefix: '/api/wellness',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Money',
    url: process.env.MONEY_URL || 'http://localhost:4724',
    prefix: '/api/money',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SUTAR Gateway',
    url: process.env.SUTAR_URL || 'http://localhost:4140',
    prefix: '/api/sutar',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'RAZO',
    url: process.env.RAZO_URL || 'http://localhost:4299',
    prefix: '/api/razo',
    healthPath: '/health',
    timeout: 5000,
    category: 'integration',
  },

  // ====== HOJAI Foundry Services ======
  {
    name: 'Creator Economy',
    url: process.env.CREATOR_ECONOMY_URL || 'http://localhost:4514',
    prefix: '/api/creator-economy',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Visual Builder',
    url: process.env.VISUAL_BUILDER_URL || 'http://localhost:4600',
    prefix: '/api/visual-builder',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },

  // ====== Genie VoiceOS Services (June 2026) ======
  {
    name: 'Meeting Intelligence',
    url: process.env.MEETING_INTELLIGENCE_URL || 'http://localhost:4890',
    prefix: '/api/meeting',
    healthPath: '/health',
    timeout: 10000,
    category: 'genie',
  },
  {
    name: 'Speaker Diarization',
    url: process.env.SPEAKER_DIARIZATION_URL || 'http://localhost:4894',
    prefix: '/api/diarization',
    healthPath: '/health',
    timeout: 10000,
    category: 'genie',
  },
  {
    name: 'Voice Embedding',
    url: process.env.VOICE_EMBEDDING_URL || 'http://localhost:4895',
    prefix: '/api/voice-embedding',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Meeting Storage',
    url: process.env.MEETING_STORAGE_URL || 'http://localhost:4896',
    prefix: '/api/meeting-storage',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Voice Cloning',
    url: process.env.VOICE_CLONING_URL || 'http://localhost:4897',
    prefix: '/api/voice-cloning',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },
  {
    name: 'Decision Twin',
    url: process.env.DECISION_TWIN_URL || 'http://localhost:4741',
    prefix: '/api/decision-twin',
    healthPath: '/health',
    timeout: 5000,
    category: 'genie',
  },

  // ====== RABTUL Financial Services (Phase 0: Week 1) ======
  {
    name: 'REZ Wallet',
    url: process.env.REZ_WALLET_URL || 'http://localhost:4004',
    prefix: '/api/wallet',
    healthPath: '/health',
    timeout: 5000,
    category: 'rabtul',
  },
  {
    name: 'REZ Payment',
    url: process.env.REZ_PAYMENT_URL || 'http://localhost:4001',
    prefix: '/api/payment',
    healthPath: '/health',
    timeout: 5000,
    category: 'rabtul',
  },
  {
    name: 'RABTUL Trust Engine',
    url: process.env.RABTUL_TRUST_URL || 'http://localhost:4180',
    prefix: '/api/trust',
    healthPath: '/health',
    timeout: 5000,
    category: 'rabtul',
  },
  {
    name: 'REZ Treasury',
    url: process.env.REZ_TREASURY_URL || 'http://localhost:4055',
    prefix: '/api/treasury',
    healthPath: '/health',
    timeout: 5000,
    category: 'rabtul',
  },
  {
    name: 'REZ Trust Scorer',
    url: process.env.REZ_TRUST_SCORER_URL || 'http://localhost:4180',
    prefix: '/api/trust/score',
    healthPath: '/health',
    timeout: 5000,
    category: 'rabtul',
  },
  {
    name: 'REZ Procurement Payment',
    url: process.env.REZ_PROCUREMENT_PAYMENT_URL || 'http://localhost:4007',
    prefix: '/api/procurement-payment',
    healthPath: '/health',
    timeout: 5000,
    category: 'rabtul',
  },

  // ====== RABTUL BNPL & Capital (Phase 0: Week 1) ======
  {
    name: 'REZ BNPL',
    url: process.env.REZ_BNPL_URL || 'http://localhost:4052',
    prefix: '/api/bnpl',
    healthPath: '/health',
    timeout: 5000,
    category: 'rabtul',
  },
  {
    name: 'REZ Capital',
    url: process.env.REZ_CAPITAL_URL || 'http://localhost:4053',
    prefix: '/api/capital',
    healthPath: '/health',
    timeout: 5000,
    category: 'rabtul',
  },
  {
    name: 'REZ Escrow',
    url: process.env.REZ_ESCROW_URL || 'http://localhost:4051',
    prefix: '/api/escrow',
    healthPath: '/health',
    timeout: 5000,
    category: 'rabtul',
  },
  {
    name: 'REZ Bill Payments',
    url: process.env.REZ_BILL_PAYMENTS_URL || 'http://localhost:4054',
    prefix: '/api/bill-payments',
    healthPath: '/health',
    timeout: 5000,
    category: 'rabtul',
  },

  // ====== SiteOS Commerce Services (Phase 0: Week 2) ======
  {
    name: 'SiteOS Product Catalog',
    url: process.env.SITEOS_CATALOG_URL || 'http://localhost:5476',
    prefix: '/api/catalog',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SiteOS Product Catalog (Alt)',
    url: process.env.SITEOS_CATALOG_URL || 'http://localhost:5476',
    prefix: '/api/products-alt',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SiteOS Cart',
    url: process.env.SITEOS_CART_URL || 'http://localhost:5477',
    prefix: '/api/cart',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SiteOS Checkout',
    url: process.env.SITEOS_CHECKOUT_URL || 'http://localhost:5478',
    prefix: '/api/checkout',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SiteOS Orders',
    url: process.env.SITEOS_CHECKOUT_URL || 'http://localhost:5478',
    prefix: '/api/orders',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SiteOS Payment Gateway',
    url: process.env.SITEOS_PAYMENT_URL || 'http://localhost:5479',
    prefix: '/api/gateway',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SiteOS Loyalty',
    url: process.env.SITEOS_LOYALTY_URL || 'http://localhost:5481',
    prefix: '/api/loyalty',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SiteOS Reviews',
    url: process.env.SITEOS_REVIEWS_URL || 'http://localhost:5480',
    prefix: '/api/reviews',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SiteOS Subscription',
    url: process.env.SITEOS_SUBSCRIPTION_URL || 'http://localhost:5494',
    prefix: '/api/subscription',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SiteOS CRM',
    url: process.env.SITEOS_CRM_URL || 'http://localhost:5484',
    prefix: '/api/crm',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SiteOS Sales Pipeline',
    url: process.env.SITEOS_PIPELINE_URL || 'http://localhost:5485',
    prefix: '/api/pipeline',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SiteOS Support',
    url: process.env.SITEOS_SUPPORT_URL || 'http://localhost:5482',
    prefix: '/api/support',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SiteOS WhatsApp',
    url: process.env.SITEOS_WHATSAPP_URL || 'http://localhost:5483',
    prefix: '/api/whatsapp',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SiteOS Analytics',
    url: process.env.SITEOS_ANALYTICS_URL || 'http://localhost:5489',
    prefix: '/api/analytics',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SiteOS Multi-Currency',
    url: process.env.SITEOS_CURRENCY_URL || 'http://localhost:5490',
    prefix: '/api/currency',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },

  // ====== Federation Services (Phase 0: Week 3) ======
  {
    name: 'Nexha Capability OS',
    url: process.env.NEXHA_CAPABILITY_URL || 'http://localhost:4270',
    prefix: '/api/capability',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Nexha Reputation OS',
    url: process.env.NEXHA_REPUTATION_URL || 'http://localhost:4271',
    prefix: '/api/reputation',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Nexha Reputation OS (ACI)',
    url: process.env.NEXHA_REPUTATION_URL || 'http://localhost:4271',
    prefix: '/api/aci',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Nexha Discovery OS',
    url: process.env.NEXHA_DISCOVERY_URL || 'http://localhost:4272',
    prefix: '/api/discovery',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Nexha ACP Messaging',
    url: process.env.NEXHA_ACP_URL || 'http://localhost:4340',
    prefix: '/api/acp',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Nexha ACP Messaging (Negotiate)',
    url: process.env.NEXHA_ACP_URL || 'http://localhost:4340',
    prefix: '/api/negotiate',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SUTAR Negotiation Engine',
    url: process.env.SUTAR_NEGOTIATION_URL || 'http://localhost:4293',
    prefix: '/api/negotiation',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SUTAR Contract OS',
    url: process.env.SUTAR_CONTRACT_URL || 'http://localhost:4292',
    prefix: '/api/contract',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Nexha Commerce Runtime',
    url: process.env.NEXHA_COMMERCE_URL || 'http://localhost:4364',
    prefix: '/api/commerce',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Nexha Business Directory',
    url: process.env.NEXHA_DIRECTORY_URL || 'http://localhost:4360',
    prefix: '/api/directory',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },

  // ====== Industry OS Services (Phase 0: Week 4) ======
  {
    name: 'Restaurant OS',
    url: process.env.RESTAURANT_OS_URL || 'http://localhost:5010',
    prefix: '/api/restaurant',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Hotel OS',
    url: process.env.HOTEL_OS_URL || 'http://localhost:5025',
    prefix: '/api/hotel',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Healthcare OS',
    url: process.env.HEALTHCARE_OS_URL || 'http://localhost:5020',
    prefix: '/api/healthcare',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Retail OS',
    url: process.env.RETAIL_OS_URL || 'http://localhost:5030',
    prefix: '/api/retail',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Legal OS',
    url: process.env.LEGAL_OS_URL || 'http://localhost:5035',
    prefix: '/api/legal',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Education OS',
    url: process.env.EDUCATION_OS_URL || 'http://localhost:5060',
    prefix: '/api/education',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Agriculture OS',
    url: process.env.AGRICULTURE_OS_URL || 'http://localhost:5070',
    prefix: '/api/agriculture',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Automotive OS',
    url: process.env.AUTOMOTIVE_OS_URL || 'http://localhost:5080',
    prefix: '/api/automotive',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Beauty OS',
    url: process.env.BEAUTY_OS_URL || 'http://localhost:5090',
    prefix: '/api/beauty',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Fashion OS',
    url: process.env.FASHION_OS_URL || 'http://localhost:5095',
    prefix: '/api/fashion',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },

  // ====== Department OS Services (Horizontal Layer) ======
  {
    name: 'Sales OS',
    url: process.env.SALES_OS_URL || 'http://localhost:5055',
    prefix: '/api/sales',
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },
  {
    name: 'Marketing OS',
    url: process.env.MARKETING_OS_URL || 'http://localhost:5500',
    prefix: '/api/marketing',
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },
  {
    name: 'Customer Success OS',
    url: process.env.CUSTOMER_SUCCESS_OS_URL || 'http://localhost:4050',
    prefix: '/api/customer-success',
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },
  {
    name: 'Procurement OS',
    url: process.env.PROCUREMENT_OS_URL || 'http://localhost:5096',
    prefix: '/api/procurement',
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },
  {
    name: 'Workforce OS',
    url: process.env.WORKFORCE_OS_URL || 'http://localhost:5077',
    prefix: '/api/workforce',
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },
  {
    name: 'Finance OS',
    url: process.env.FINANCE_OS_URL || 'http://localhost:4801',
    prefix: '/api/finance',
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },
  {
    name: 'Operations OS',
    url: process.env.OPERATIONS_OS_URL || 'http://localhost:5250',
    prefix: '/api/operations',
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },
  {
    name: 'CXO OS',
    url: process.env.CXO_OS_URL || 'http://localhost:5100',
    prefix: '/api/cxo',
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },
  {
    name: 'Revenue Intelligence OS',
    url: process.env.REVENUE_OS_URL || 'http://localhost:5400',
    prefix: '/api/revenue',
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },

  // ====== CompanyOS Services (Phase 0: Week 4) ======
  {
    name: 'Company OS',
    url: process.env.COMPANY_OS_URL || 'http://localhost:4010',
    prefix: '/api/company',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'Company Factory',
    url: process.env.COMPANY_FACTORY_URL || 'http://localhost:4010',
    prefix: '/api/factory',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SUTAR Gateway',
    url: process.env.SUTAR_GATEWAY_URL || 'http://localhost:4140',
    prefix: '/api/sutar-gateway',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SUTAR Decision Engine',
    url: process.env.SUTAR_DECISION_URL || 'http://localhost:4290',
    prefix: '/api/sutar/decision',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },
  {
    name: 'SUTAR Trust Engine',
    url: process.env.SUTAR_TRUST_URL || 'http://localhost:4291',
    prefix: '/api/sutar/trust',
    healthPath: '/health',
    timeout: 5000,
    category: 'rtmn',
  },

  // ====== Unified CommerceOS Gateway (Phase 1) ======
  {
    name: 'CommerceOS Gateway',
    url: process.env.COMMERCE_OS_URL || 'http://localhost:5400',
    prefix: '/api/commerce-os',
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },

  // ====== BAM Gateway + Workers (Phase 2) ======
  {
    name: 'BAM Gateway',
    url: process.env.BAM_GATEWAY_URL || 'http://localhost:5550',
    prefix: '/api/bam',
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },
  {
    name: 'Vendor Acquisition Worker',
    url: process.env.VENDOR_ACQUISITION_URL || 'http://localhost:5551',
    prefix: '/api/bam/vendor-acquisition',
    healthPath: '/health',
    timeout: 30000,
    category: 'rtmn',
  },
  {
    name: 'Catalog Normalization Worker',
    url: process.env.CATALOG_NORMALIZATION_URL || 'http://localhost:5552',
    prefix: '/api/bam/catalog-normalization',
    healthPath: '/health',
    timeout: 30000,
    category: 'rtmn',
  },
  {
    name: 'Recommendation Worker',
    url: process.env.RECOMMENDATION_WORKER_URL || 'http://localhost:5553',
    prefix: '/api/bam/recommendation',
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },

  // ====== Template Engine + Vendor Pools (Phase 3) ======
  {
    name: 'Template Engine',
    url: process.env.TEMPLATE_ENGINE_URL || 'http://localhost:5670',
    prefix: '/api/templates',
    stripPrefix: false,
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },
  {
    name: 'Vendor Liquidity Pools',
    url: process.env.VENDOR_POOLS_URL || 'http://localhost:5680',
    prefix: '/api/pools',
    stripPrefix: false,
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },

  // ====== Commerce Studio (Phase 4) ======
  {
    name: 'Commerce Studio Backend',
    url: process.env.STUDIO_BACKEND_URL || 'http://localhost:5750',
    prefix: '/api/studio',
    stripPrefix: false,
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },

  // ====== Phase 5: Advanced Commerce Services ======
  {
    name: 'Product Graph',
    url: process.env.PRODUCT_GRAPH_URL || 'http://localhost:5800',
    prefix: '/api/products',
    stripPrefix: false,
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },
  {
    name: 'Trade Finance',
    url: process.env.TRADE_FINANCE_URL || 'http://localhost:5810',
    prefix: '/api/trade-finance',
    stripPrefix: false,
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },
  {
    name: 'Cross-Border Commerce',
    url: process.env.CROSS_BORDER_URL || 'http://localhost:5820',
    prefix: '/api/cross-border',
    stripPrefix: false,
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },
  {
    name: 'Universal Distribution',
    url: process.env.UNIVERSAL_DISTRIBUTION_URL || 'http://localhost:5830',
    prefix: '/api/distribution',
    stripPrefix: false,
    healthPath: '/health',
    timeout: 10000,
    category: 'rtmn',
  },

  // ====== HOJAI InternetOS (Web Intelligence Platform) ======
  {
    name: 'InternetOS API',
    url: process.env.INTERNETOS_URL || 'http://localhost:4595',
    prefix: '/api/internet-os',
    healthPath: '/health',
    timeout: 30000, // Scraping can take longer
    category: 'integration',
  },
  {
    name: 'InternetOS Watchers',
    url: process.env.INTERNETOS_URL || 'http://localhost:4595',
    prefix: '/api/watchers',
    healthPath: '/health',
    timeout: 10000,
    category: 'integration',
  },
  {
    name: 'InternetOS Research Agents',
    url: process.env.INTERNETOS_URL || 'http://localhost:4595',
    prefix: '/api/research',
    healthPath: '/health',
    timeout: 60000, // Research can take longer
    category: 'integration',
  },
  {
    name: 'InternetOS Scheduler',
    url: process.env.INTERNETOS_URL || 'http://localhost:4595',
    prefix: '/api/scheduler',
    healthPath: '/health',
    timeout: 10000,
    category: 'integration',
  },
  {
    name: 'InternetOS History',
    url: process.env.INTERNETOS_URL || 'http://localhost:4595',
    prefix: '/api/history',
    healthPath: '/health',
    timeout: 10000,
    category: 'integration',
  },
];

export function findService(prefix: string): ServiceEntry | undefined {
  return SERVICE_REGISTRY.find(s => s.prefix === prefix);
}

export function findServiceByPath(path: string): ServiceEntry | undefined {
  const candidates = SERVICE_REGISTRY.filter(s => path.startsWith(s.prefix));

  if (candidates.length === 0) return undefined;
  if (candidates.length === 1) return candidates[0];

  // Multiple matches — pick the longest prefix (most specific).
  // Use reduce (not sort) to avoid mutating the registry array and to be deterministic
  // when two prefixes have the same length (first registered wins).
  return candidates.reduce((best, current) =>
    current.prefix.length > best.prefix.length ? current : best
  );
}