/**
 * Healthcare Patient App API
 * Generated by HOJAI Studio
 *
 * Features:
 * - Doctor search & booking
 * - Telemedicine consultations
 * - Health records
 * - Prescriptions
 * - Lab tests
 */
import express from 'express';
import cors from 'cors';
import { v4 as uuidv4 } from 'uuid';

const app = express();
app.use(cors(), express.json());
const PORT = process.env.PORT || 3000;

// ── Sample Data ───────────────────────────────────────────────────────────────

const doctors = [
  { id: 'doc1', name: 'Dr. Rajesh Kumar', specialty: 'General Physician', hospital: 'Apollo Hospital', experience: 15, rating: 4.8, fees: 500, image: 'https://picsum.photos/200/200?50', available: true },
  { id: 'doc2', name: 'Dr. Priya Sharma', specialty: 'Cardiologist', hospital: 'Fortis Hospital', experience: 12, rating: 4.9, fees: 1000, image: 'https://picsum.photos/200/200?51', available: true },
  { id: 'doc3', name: 'Dr. Amit Singh', specialty: 'Dermatologist', hospital: 'Max Hospital', experience: 8, rating: 4.7, fees: 800, image: 'https://picsum.photos/200/200?52', available: true },
  { id: 'doc4', name: 'Dr. Neha Patel', specialty: 'Pediatrician', hospital: 'Medanta', experience: 10, rating: 4.8, fees: 700, image: 'https://picsum.photos/200/200?53', available: false },
  { id: 'doc5', name: 'Dr. Vikram Rao', specialty: 'Orthopedic', hospital: 'Artemis Hospital', experience: 18, rating: 4.9, fees: 1200, image: 'https://picsum.photos/200/200?54', available: true },
];

const appointments = new Map();
const prescriptions = new Map();
const records = new Map();

// ── Routes ─────────────────────────────────────────────────────────────────────

app.get('/health', (_, res) => res.json({ status: 'ok', app: 'healthcare-patient' }));

// Specialties
app.get('/api/specialties', (_, res) => {
  const specialties = [...new Set(doctors.map(d => d.specialty))];
  res.json({ success: true, specialties });
});

// Doctors
app.get('/api/doctors', (req, res) => {
  const { specialty, search, available } = req.query;
  let results = [...doctors];

  if (specialty) results = results.filter(d => d.specialty.toLowerCase().includes(specialty.toLowerCase()));
  if (search) results = results.filter(d => d.name.toLowerCase().includes(search.toLowerCase()) || d.specialty.toLowerCase().includes(search.toLowerCase()));
  if (available === 'true') results = results.filter(d => d.available);

  res.json({ success: true, doctors: results });
});

app.get('/api/doctors/:id', (req, res) => {
  const doctor = doctors.find(d => d.id === req.params.id);
  if (!doctor) return res.status(404).json({ error: 'Doctor not found' });
  res.json({ success: true, doctor });
});

// Get doctor availability slots
app.get('/api/doctors/:id/slots', (req, res) => {
  const { date } = req.query;
  const slots = [];
  const hours = [9, 10, 11, 14, 15, 16, 17, 18];

  for (const hour of hours) {
    const time = `${hour.toString().padStart(2, '0')}:00`;
    slots.push({
      time,
      available: Math.random() > 0.3
    });
    if (hour < 12 || hour >= 14) {
      slots.push({
        time: `${hour.toString().padStart(2, '0')}:30`,
        available: Math.random() > 0.4
      });
    }
  }

  res.json({ success: true, date: date || new Date().toISOString().split('T')[0], slots });
});

// Symptom checker
app.post('/api/symptom-check', (req, res) => {
  const { symptoms } = req.body;

  // Mock symptom analysis
  const specialtyMap = {
    fever: 'General Physician',
    headache: 'General Physician',
    chest_pain: 'Cardiologist',
    skin_rash: 'Dermatologist',
    child_health: 'Pediatrician',
    bone_joint: 'Orthopedic'
  };

  const matched = symptoms.map(s => specialtyMap[s.toLowerCase()] || 'General Physician');
  const recommended = [...new Set(matched)];

  res.json({
    success: true,
    analysis: {
      symptoms,
      urgency: symptoms.includes('chest_pain') ? 'emergency' : symptoms.length > 3 ? 'high' : 'normal',
      recommendedSpecialties: recommended,
      advice: 'Please consult a doctor for proper diagnosis.'
    }
  });
});

// Book appointment
app.post('/api/appointments', (req, res) => {
  const { patientId, doctorId, date, time, type = 'in-clinic' } = req.body;

  if (!patientId || !doctorId || !date || !time) {
    return res.status(400).json({ error: 'patientId, doctorId, date, and time required' });
  }

  const doctor = doctors.find(d => d.id === doctorId);
  if (!doctor) return res.status(404).json({ error: 'Doctor not found' });

  const appointment = {
    id: `APT${Date.now()}`,
    patientId,
    doctorId,
    doctorName: doctor.name,
    specialty: doctor.specialty,
    hospital: doctor.hospital,
    date,
    time,
    type,
    status: 'confirmed',
    fees: doctor.fees,
    meetingLink: type === 'tele' ? `https://meet.healthcare.app/${uuidv4()}` : null,
    createdAt: new Date().toISOString()
  };

  appointments.set(appointment.id, appointment);

  res.status(201).json({ success: true, appointment });
});

app.get('/api/appointments/:patientId', (req, res) => {
  const patientAppts = Array.from(appointments.values())
    .filter(a => a.patientId === req.params.patientId)
    .sort((a, b) => new Date(b.date) - new Date(a.date));
  res.json({ success: true, appointments: patientAppts });
});

app.get('/api/appointments/:patientId/:id', (req, res) => {
  const appt = appointments.get(req.params.id);
  if (!appt || appt.patientId !== req.params.patientId) {
    return res.status(404).json({ error: 'Appointment not found' });
  }
  res.json({ success: true, appointment: appt });
});

app.post('/api/appointments/:id/cancel', (req, res) => {
  const appt = appointments.get(req.params.id);
  if (!appt) return res.status(404).json({ error: 'Appointment not found' });

  appt.status = 'cancelled';
  appt.cancelledAt = new Date().toISOString();
  appointments.set(appt.id, appt);

  res.json({ success: true, appointment: appt });
});

// Prescriptions
app.get('/api/prescriptions/:patientId', (req, res) => {
  const patientRx = Array.from(prescriptions.values())
    .filter(p => p.patientId === req.params.patientId)
    .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
  res.json({ success: true, prescriptions: patientRx });
});

app.post('/api/prescriptions', (req, res) => {
  const { patientId, doctorId, doctorName, medicines, notes } = req.body;

  const prescription = {
    id: `RX${Date.now()}`,
    patientId,
    doctorId,
    doctorName,
    medicines,
    notes,
    status: 'active',
    createdAt: new Date().toISOString()
  };

  prescriptions.set(prescription.id, prescription);
  res.status(201).json({ success: true, prescription });
});

// Health Records
app.get('/api/records/:patientId', (req, res) => {
  const patientRecords = records.get(req.params.patientId) || [];
  res.json({ success: true, records: patientRecords });
});

app.post('/api/records', (req, res) => {
  const { patientId, type, title, data, date } = req.body;

  if (!records.has(patientId)) records.set(patientId, []);

  const record = {
    id: uuidv4(),
    patientId,
    type,
    title,
    data,
    date: date || new Date().toISOString(),
    createdAt: new Date().toISOString()
  };

  records.get(patientId).push(record);
  res.status(201).json({ success: true, record });
});

// Lab Tests
app.get('/api/labs', (_, res) => {
  res.json({
    success: true,
    labs: [
      { id: 'l1', name: 'Thyrocare', tests: 100, price: 500, homeCollection: true },
      { id: 'l2', name: 'Dr Lal Pathlabs', tests: 150, price: 600, homeCollection: true },
      { id: 'l3', name: 'Metropolis', tests: 200, price: 800, homeCollection: true }
    ]
  });
});

app.get('/api/lab-tests', (_, res) => {
  res.json({
    success: true,
    tests: [
      { id: 't1', name: 'Complete Blood Count (CBC)', price: 300, fasting: false },
      { id: 't2', name: 'Lipid Profile', price: 400, fasting: true },
      { id: 't3', name: 'Thyroid Profile (T3, T4, TSH)', price: 500, fasting: true },
      { id: 't4', name: 'HbA1c (Diabetes)', price: 350, fasting: false },
      { id: 't5', name: 'Vitamin D', price: 600, fasting: false },
      { id: 't6', name: 'Full Body Checkup', price: 2500, fasting: true }
    ]
  });
});

app.post('/api/labs/book', (req, res) => {
  const { patientId, labId, tests, address, date } = req.body;

  const booking = {
    id: `LAB${Date.now()}`,
    patientId,
    labId,
    tests,
    address,
    date,
    status: 'confirmed',
    homeCollection: true,
    createdAt: new Date().toISOString()
  };

  res.status(201).json({ success: true, booking });
});

// Insurance
app.post('/api/insurance/verify', (req, res) => {
  const { policyNumber } = req.body;

  // Mock verification
  res.json({
    success: true,
    insurance: {
      policyNumber,
      provider: 'HDFC ERGO',
      status: 'active',
      coverage: 500000,
      remaining: 450000,
      copay: 0.1
    }
  });
});

app.listen(PORT, () => {
  console.log(`
╔══════════════════════════════════════════════════════════════╗
║  🏥  Healthcare Patient App — PORT ${PORT}                 ║
║  AI-powered like Practo                            ║
╠══════════════════════════════════════════════════════════════╣
║  Doctors: ${doctors.length}                                             ║
║  Specialties: ${[...new Set(doctors.map(d => d.specialty))].length}                                               ║
╚══════════════════════════════════════════════════════════════╝
  `);
});

export default app;
