/**
 * OTA Mobile App - Home Screen
 * Generated by HOJAI Studio
 */
import React, { useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  SafeAreaView,
  StatusBar,
} from 'react-native';

// Navigation
const NAV = {
  HOTELS: 'Hotels',
  FLIGHTS: 'Flights',
  PACKAGES: 'Packages',
  TRIPS: 'My Trips',
};

interface Hotel {
  id: string;
  name: string;
  city: string;
  price: number;
  rating: number;
  image: string;
  amenities: string[];
}

interface Flight {
  id: string;
  airline: string;
  from: string;
  to: string;
  depart: string;
  arrive: string;
  price: number;
}

export default function HomeScreen({ navigation }: any) {
  const [searchType, setSearchType] = useState('hotels');
  const [destination, setDestination] = useState('');
  const [checkIn, setCheckIn] = useState('');
  const [checkOut, setCheckOut] = useState('');
  const [guests, setGuests] = useState('2');
  const [loading, setLoading] = useState(false);

  // Sample data
  const featuredHotels: Hotel[] = [
    { id: '1', name: 'Taj Palace', city: 'Mumbai', price: 8500, rating: 4.8, image: '🏨', amenities: ['pool', 'spa'] },
    { id: '2', name: 'Marriott Suites', city: 'Delhi', price: 7200, rating: 4.6, image: '🏨', amenities: ['gym', 'wifi'] },
    { id: '3', name: 'ITC Grand', city: 'Bangalore', price: 9500, rating: 4.9, image: '🏨', amenities: ['pool', 'spa'] },
    { id: '4', name: 'Leela Palace', city: 'Goa', price: 12000, rating: 4.9, image: '🏨', amenities: ['beach', 'pool'] },
  ];

  const handleSearch = async () => {
    setLoading(true);
    // TODO: Call backend API
    setTimeout(() => {
      setLoading(false);
      navigation.navigate('Results', { type: searchType, destination });
    }, 1000);
  };

  const renderSearchBar = () => (
    <View style={styles.searchBar}>
      <View style={styles.searchTabs}>
        {['hotels', 'flights', 'packages'].map((tab) => (
          <TouchableOpacity
            key={tab}
            style={[styles.searchTab, searchType === tab && styles.searchTabActive]}
            onPress={() => setSearchType(tab)}
          >
            <Text style={[styles.searchTabText, searchType === tab && styles.searchTabTextActive]}>
              {tab === 'hotels' ? '🏨 Hotels' : tab === 'flights' ? '✈️ Flights' : '📦 Packages'}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      <View style={styles.searchInputs}>
        <View style={styles.inputContainer}>
          <Text style={styles.inputLabel}>
            {searchType === 'hotels' ? '📍 Destination' : searchType === 'flights' ? '🏙️ City' : '🎯 Destination'}
          </Text>
          <TextInput
            style={styles.input}
            placeholder={searchType === 'hotels' ? 'Search hotels...' : searchType === 'flights' ? 'Search flights...' : 'Search packages...'}
            value={destination}
            onChangeText={setDestination}
          />
        </View>

        <View style={styles.dateRow}>
          <View style={styles.dateInput}>
            <Text style={styles.inputLabel}>📅 Check-in</Text>
            <TextInput style={styles.input} placeholder="Select date" value={checkIn} onChangeText={setCheckIn} />
          </View>
          <View style={styles.dateInput}>
            <Text style={styles.inputLabel}>📅 Check-out</Text>
            <TextInput style={styles.input} placeholder="Select date" value={checkOut} onChangeText={setCheckOut} />
          </View>
        </View>

        <View style={styles.inputContainer}>
          <Text style={styles.inputLabel}>👥 Guests</Text>
          <TextInput style={styles.input} placeholder="2" value={guests} onChangeText={setGuests} keyboardType="numeric" />
        </View>

        <TouchableOpacity style={styles.searchButton} onPress={handleSearch} disabled={loading}>
          <Text style={styles.searchButtonText}>{loading ? '🔍 Searching...' : '🔍 Search'}</Text>
        </TouchableOpacity>
      </View>
    </View>
  );

  const renderFeaturedHotels = () => (
    <View style={styles.section}>
      <View style={styles.sectionHeader}>
        <Text style={styles.sectionTitle}>🏨 Featured Hotels</Text>
        <TouchableOpacity onPress={() => navigation.navigate('Results', { type: 'hotels' })}>
          <Text style={styles.seeAll}>See All →</Text>
        </TouchableOpacity>
      </View>
      <ScrollView horizontal showsHorizontalScrollIndicator={false}>
        {featuredHotels.map((hotel) => (
          <TouchableOpacity
            key={hotel.id}
            style={styles.hotelCard}
            onPress={() => navigation.navigate('HotelDetail', { hotel })}
          >
            <View style={styles.hotelImage}>{/* Image placeholder */}</View>
            <Text style={styles.hotelEmoji}>🏨</Text>
            <Text style={styles.hotelName}>{hotel.name}</Text>
            <Text style={styles.hotelCity}>{hotel.city}</Text>
            <View style={styles.hotelFooter}>
              <Text style={styles.hotelRating}>⭐ {hotel.rating}</Text>
              <Text style={styles.hotelPrice}>₹{hotel.price.toLocaleString()}</Text>
            </View>
          </TouchableOpacity>
        ))}
      </ScrollView>
    </View>
  );

  const renderQuickActions = () => (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>⚡ Quick Actions</Text>
      <View style={styles.quickActions}>
        <TouchableOpacity style={styles.quickAction} onPress={() => setSearchType('flights')}>
          <Text style={styles.quickActionIcon}>✈️</Text>
          <Text style={styles.quickActionText}>Flights</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.quickAction} onPress={() => setSearchType('hotels')}>
          <Text style={styles.quickActionIcon}>🏨</Text>
          <Text style={styles.quickActionText}>Hotels</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.quickAction} onPress={() => navigation.navigate('TripPlanner')}>
          <Text style={styles.quickActionIcon}>🤖</Text>
          <Text style={styles.quickActionText}>AI Planner</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.quickAction} onPress={() => navigation.navigate('MyTrips')}>
          <Text style={styles.quickActionIcon}>📋</Text>
          <Text style={styles.quickActionText}>My Trips</Text>
        </TouchableOpacity>
      </View>
    </View>
  );

  const renderPromo = () => (
    <View style={styles.promoCard}>
      <Text style={styles.promoTitle}>🤖 AI Trip Planner</Text>
      <Text style={styles.promoDesc}>Tell us your dream trip and we'll plan it for you!</Text>
      <TouchableOpacity style={styles.promoButton} onPress={() => navigation.navigate('TripPlanner')}>
        <Text style={styles.promoButtonText}>Try AI Planner →</Text>
      </TouchableOpacity>
    </View>
  );

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="dark-content" backgroundColor="#fff" />
      <ScrollView showsVerticalScrollIndicator={false}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.logo}>✈️ TravelMate AI</Text>
          <TouchableOpacity style={styles.profileButton}>
            <Text style={styles.profileEmoji}>👤</Text>
          </TouchableOpacity>
        </View>

        {renderSearchBar()}
        {renderPromo()}
        {renderFeaturedHotels()}
        {renderQuickActions()}

        {/* AI Features */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>🤖 AI Features</Text>
          <View style={styles.aiFeatures}>
            <View style={styles.aiFeature}>
              <Text style={styles.aiFeatureIcon}>🧠</Text>
              <Text style={styles.aiFeatureTitle}>Smart Search</Text>
              <Text style={styles.aiFeatureDesc}>AI-powered recommendations</Text>
            </View>
            <View style={styles.aiFeature}>
              <Text style={styles.aiFeatureIcon}>💰</Text>
              <Text style={styles.aiFeatureTitle}>Price Predict</Text>
              <Text style={styles.aiFeatureDesc}>Know when to book</Text>
            </View>
            <View style={styles.aiFeature}>
              <Text style={styles.aiFeatureIcon}>🛡️</Text>
              <Text style={styles.aiFeatureTitle}>Smart Cover</Text>
              <Text style={styles.aiFeatureDesc}>AI travel insurance</Text>
            </View>
          </View>
        </View>
      </ScrollView>

      {/* Bottom Tab */}
      <View style={styles.bottomTab}>
        <TouchableOpacity style={styles.tabItem}>
          <Text style={styles.tabIcon}>🏠</Text>
          <Text style={styles.tabLabel}>Home</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.tabItem} onPress={() => navigation.navigate('MyTrips')}>
          <Text style={styles.tabIcon}>📋</Text>
          <Text style={styles.tabLabel}>Trips</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.tabItem} onPress={() => navigation.navigate('TripPlanner')}>
          <Text style={styles.tabIcon}>🤖</Text>
          <Text style={styles.tabLabel}>AI</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.tabItem}>
          <Text style={styles.tabIcon}>👤</Text>
          <Text style={styles.tabLabel}>Profile</Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, backgroundColor: '#fff' },
  logo: { fontSize: 22, fontWeight: 'bold', color: '#0284c7' },
  profileButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#e0e0e0', justifyContent: 'center', alignItems: 'center' },
  profileEmoji: { fontSize: 20 },
  searchBar: { backgroundColor: '#0284c7', padding: 16, paddingBottom: 24, borderBottomLeftRadius: 24, borderBottomRightRadius: 24 },
  searchTabs: { flexDirection: 'row', justifyContent: 'center', marginBottom: 16 },
  searchTab: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.2)', marginHorizontal: 4 },
  searchTabActive: { backgroundColor: '#fff' },
  searchTabText: { color: '#fff', fontWeight: '500' },
  searchTabTextActive: { color: '#0284c7' },
  searchInputs: { backgroundColor: '#fff', borderRadius: 16, padding: 16 },
  inputContainer: { marginBottom: 12 },
  inputLabel: { fontSize: 12, color: '#666', marginBottom: 4 },
  input: { borderWidth: 1, borderColor: '#e0e0e0', borderRadius: 8, padding: 12, fontSize: 16 },
  dateRow: { flexDirection: 'row', marginBottom: 12 },
  dateInput: { flex: 1, marginRight: 8 },
  searchButton: { backgroundColor: '#0284c7', borderRadius: 8, padding: 14, alignItems: 'center', marginTop: 4 },
  searchButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  promoCard: { backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', margin: 16, padding: 20, borderRadius: 16 },
  promoTitle: { fontSize: 20, fontWeight: 'bold', color: '#fff', marginBottom: 8 },
  promoDesc: { color: 'rgba(255,255,255,0.8)', marginBottom: 12 },
  promoButton: { backgroundColor: '#fff', padding: 10, borderRadius: 8, alignSelf: 'flex-start' },
  promoButtonText: { color: '#764ba2', fontWeight: '600' },
  section: { padding: 16 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', color: '#333' },
  seeAll: { color: '#0284c7', fontSize: 14 },
  hotelCard: { width: 180, backgroundColor: '#fff', borderRadius: 12, padding: 12, marginRight: 12, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  hotelImage: { height: 100, backgroundColor: '#e0e0e0', borderRadius: 8, marginBottom: 8, justifyContent: 'center', alignItems: 'center' },
  hotelEmoji: { fontSize: 40, textAlign: 'center' },
  hotelName: { fontSize: 14, fontWeight: '600', marginTop: 4 },
  hotelCity: { fontSize: 12, color: '#666' },
  hotelFooter: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
  hotelRating: { fontSize: 12 },
  hotelPrice: { fontSize: 14, fontWeight: 'bold', color: '#0284c7' },
  quickActions: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 8 },
  quickAction: { width: '25%', alignItems: 'center', padding: 8 },
  quickActionIcon: { fontSize: 28, marginBottom: 4 },
  quickActionText: { fontSize: 12, color: '#666' },
  aiFeatures: { flexDirection: 'row', marginTop: 8 },
  aiFeature: { flex: 1, backgroundColor: '#fff', borderRadius: 12, padding: 12, marginRight: 8, alignItems: 'center' },
  aiFeatureIcon: { fontSize: 28, marginBottom: 8 },
  aiFeatureTitle: { fontSize: 12, fontWeight: '600' },
  aiFeatureDesc: { fontSize: 10, color: '#666', textAlign: 'center' },
  bottomTab: { flexDirection: 'row', backgroundColor: '#fff', padding: 8, borderTopWidth: 1, borderTopColor: '#e0e0e0' },
  tabItem: { flex: 1, alignItems: 'center', padding: 8 },
  tabIcon: { fontSize: 24 },
  tabLabel: { fontSize: 10, color: '#666', marginTop: 2 },
});
