/**
 * E-Commerce Seller App API
 * Generated by HOJAI Studio
 *
 * Features:
 * - Product management
 * - Order management
 * - Seller dashboard
 * - Payouts
 */
import express from 'express';
import cors from 'cors';
import { v4 as uuidv4 } from 'uuid';

const app = express();

// ── Internal Auth ────────────────────────────────────────────────
function requireInternal(req, res, next) {
  const token = req.headers['x-internal-token'];
  const expected = process.env.INTERNAL_SERVICE_TOKEN;
  if (token && expected && token === expected) {
    req.user = { type: 'service', id: 'internal' };
    return next();
  }
  return res.status(401).json({ error: 'Unauthorized' });
}

app.use(cors(), express.json());
const PORT = process.env.PORT || 3001;

// ── In-Memory Database ─────────────────────────────────────────────────────────

const sellers = new Map();
const sellerProducts = new Map();
const sellerOrders = new Map();
const payouts = new Map();

// Sample seller
const sampleSeller = {
  id: 's1',
  name: 'TechStore India',
  email: 'seller@techstore.in',
  phone: '+919876543210',
  rating: 4.6,
  totalSales: 1250,
  revenue: 2450000,
  pendingPayout: 45000,
  status: 'active'
};
sellers.set(sampleSeller.id, sampleSeller);

// Sample products
sellerProducts.set(sampleSeller.id, [
  { id: 'sp1', name: 'iPhone 15 Pro', price: 99900, stock: 50, sold: 125, status: 'active' },
  { id: 'sp2', name: 'Samsung Galaxy S24', price: 109999, stock: 35, sold: 89, status: 'active' },
  { id: 'sp3', name: 'MacBook Air M3', price: 114900, stock: 25, sold: 45, status: 'active' }
]);

// ── Routes ─────────────────────────────────────────────────────────────────────

app.get('/health', (_, res) => res.json({ status: 'ok', app: 'ecommerce-seller' }));

// Dashboard
app.get('/api/seller/:id/dashboard', (req, res) => {
  const seller = sellers.get(req.params.id);
  if (!seller) return res.status(404).json({ error: 'Seller not found' });

  const products = sellerProducts.get(req.params.id) || [];
  const orders = sellerOrders.get(req.params.id) || [];

  res.json({
    success: true,
    dashboard: {
      totalSales: seller.totalSales,
      revenue: seller.revenue,
      pendingPayout: seller.pendingPayout,
      rating: seller.rating,
      activeProducts: products.filter(p => p.status === 'active').length,
      pendingOrders: orders.filter(o => o.status === 'pending').length
    }
  });
});

// Products
app.get('/api/seller/:id/products', (req, res) => {
  const products = sellerProducts.get(req.params.id) || [];
  res.json({ success: true, products });
});

app.post('/api/seller/:id/products', requireInternal, (req, res) => {
  const product = {
    id: uuidv4(),
    sellerId: req.params.id,
    ...req.body,
    sold: 0,
    status: 'active',
    createdAt: new Date().toISOString()
  };

  if (!sellerProducts.has(req.params.id)) {
    sellerProducts.set(req.params.id, []);
  }
  sellerProducts.get(req.params.id).push(product);

  res.status(201).json({ success: true, product });
});

app.put('/api/seller/:id/products/:productId', requireInternal, (req, res) => {
  const products = sellerProducts.get(req.params.id);
  if (!products) return res.status(404).json({ error: 'Products not found' });

  const idx = products.findIndex(p => p.id === req.params.productId);
  if (idx === -1) return res.status(404).json({ error: 'Product not found' });

  products[idx] = { ...products[idx], ...req.body };
  res.json({ success: true, product: products[idx] });
});

app.delete('/api/seller/:id/products/:productId', requireInternal, (req, res) => {
  const products = sellerProducts.get(req.params.id);
  if (!products) return res.status(404).json({ error: 'Products not found' });

  const idx = products.findIndex(p => p.id === req.params.productId);
  if (idx > -1) products.splice(idx, 1);

  res.json({ success: true });
});

// Orders
app.get('/api/seller/:id/orders', (req, res) => {
  const orders = sellerOrders.get(req.params.id) || [];
  res.json({ success: true, orders });
});

app.put('/api/seller/:id/orders/:orderId', requireInternal, (req, res) => {
  const orders = sellerOrders.get(req.params.id) || [];
  const order = orders.find(o => o.id === req.params.orderId);
  if (!order) return res.status(404).json({ error: 'Order not found' });

  order.status = req.body.status;
  order.updatedAt = new Date().toISOString();

  res.json({ success: true, order });
});

// Payouts
app.get('/api/seller/:id/payouts', (req, res) => {
  const sellerPayouts = payouts.get(req.params.id) || [];
  res.json({ success: true, payouts: sellerPayouts });
});

app.listen(PORT, () => {
  console.log(`
╔══════════════════════════════════════════════════════════════╗
║  🛒  E-Commerce Seller App — PORT ${PORT}                    ║
║  Product & Order Management for Sellers                   ║
╚══════════════════════════════════════════════════════════════╝
  `);
});

export default app;
