# RAZO Keyboard iOS Dependencies
# Run: pod install

platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
  # Networking
  pod 'Alamofire', '~> 5.8'

  # Keychain
  pod 'KeychainAccess', '~> 4.2'

  # Auto Layout
  pod 'SnapKit', '~> 5.6'
end

target 'RAZOKeyboardApp' do
  shared_pods

  # Analytics
  pod 'Firebase/Analytics', '~> 10.0'
end

target 'RAZOKeyboardExtension' do
  shared_pods

  # Speech recognition (built-in, no pod needed)
  # LocalAuthentication (built-in, no pod needed)
end

target 'RAZOCredentialProvider' do
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
