/**
 * E-Commerce Buyer App API
 * Generated by HOJAI Studio
 *
 * Features:
 * - Product browsing & search
 * - Cart management
 * - Checkout & payments
 * - Order tracking
 * - Wishlist
 * - Reviews & ratings
 */
import express from 'express';
import cors from 'cors';
import { v4 as uuidv4 } from 'uuid';

const app = express();

// ── Internal Auth ────────────────────────────────────────────────
function requireInternal(req, res, next) {
  const token = req.headers['x-internal-token'];
  const expected = process.env.INTERNAL_SERVICE_TOKEN;
  if (token && expected && token === expected) {
    req.user = { type: 'service', id: 'internal' };
    return next();
  }
  return res.status(401).json({ error: 'Unauthorized' });
}

app.use(cors(), express.json());
const PORT = process.env.PORT || 3000;

// ── In-Memory Database ───────────────────────────────────────────────────────────

const products = [
  // Electronics
  { id: 'p1', name: 'iPhone 15 Pro', category: 'electronics', price: 99900, originalPrice: 119900, rating: 4.8, reviews: 2453, stock: 50, seller: 'apple_store', images: ['https://picsum.photos/400/400?1'], description: 'Latest iPhone with A17 Pro chip', badges: ['bestseller', 'prime'] },
  { id: 'p2', name: 'Samsung Galaxy S24 Ultra', category: 'electronics', price: 109999, originalPrice: 129999, rating: 4.7, reviews: 1823, stock: 35, seller: 'samsung_india', images: ['https://picsum.photos/400/400?2'], description: '200MP camera with S Pen', badges: ['new'] },
  { id: 'p3', name: 'MacBook Air M3', category: 'electronics', price: 114900, originalPrice: 129900, rating: 4.9, reviews: 892, stock: 25, seller: 'apple_store', images: ['https://picsum.photos/400/400?3'], description: 'Supercharged by M3 chip', badges: ['prime'] },
  { id: 'p4', name: 'Sony WH-1000XM5', category: 'electronics', price: 24990, originalPrice: 34990, rating: 4.8, reviews: 4521, stock: 100, seller: 'sony_hub', images: ['https://picsum.photos/400/400?4'], description: 'Industry-leading noise cancellation', badges: ['deal'] },

  // Fashion
  { id: 'p5', name: "Levi's 511 Slim Fit Jeans", category: 'fashion', price: 1999, originalPrice: 3999, rating: 4.5, reviews: 8923, stock: 200, seller: 'levis_in', images: ['https://picsum.photos/400/400?5'], description: 'Classic slim fit jeans', badges: ['bestseller'] },
  { id: 'p6', name: 'Nike Air Max 270', category: 'fashion', price: 8995, originalPrice: 11995, rating: 4.7, reviews: 3421, stock: 150, seller: 'nike_india', images: ['https://picsum.photos/400/400?6'], description: 'Max Air cushioning', badges: ['prime'] },
  { id: 'p7', name: 'Wildcraft Backpack 45L', category: 'fashion', price: 1499, originalPrice: 2499, rating: 4.4, reviews: 5621, stock: 80, seller: 'wildcraft', images: ['https://picsum.photos/400/400?7'], description: 'Waterproof laptop backpack', badges: ['deal'] },

  // Home & Kitchen
  { id: 'p8', name: 'Prestige Iris 1.8L Rice Cooker', category: 'home', price: 2995, originalPrice: 4495, rating: 4.6, reviews: 2134, stock: 60, seller: 'home_essentials', images: ['https://picsum.photos/400/400?8'], description: 'Automatic rice cooker with keep warm', badges: [] },
  { id: 'p9', name: 'Milton Thermosteel Flask 1L', category: 'home', price: 699, originalPrice: 999, rating: 4.5, reviews: 8923, stock: 300, seller: 'milton_india', images: ['https://picsum.photos/400/400?9'], description: 'Stainless steel vacuum flask', badges: ['bestseller'] },

  // Books
  { id: 'p10', name: 'Atomic Habits by James Clear', category: 'books', price: 399, originalPrice: 699, rating: 4.9, reviews: 45234, stock: 500, seller: 'bookstore', images: ['https://picsum.photos/400/400?10'], description: 'Build good habits, break bad ones', badges: ['bestseller'] },

  // Groceries
  { id: 'p11', name: 'Tata Sampann Masala Combo', category: 'groceries', price: 299, originalPrice: 450, rating: 4.6, reviews: 2341, stock: 200, seller: 'grocery_hub', images: ['https://picsum.photos/400/400?11'], description: 'Premium spice combo pack', badges: [] }
];

const carts = new Map();
const orders = new Map();
const wishlists = new Map();
const reviews = new Map();

// ── Routes ─────────────────────────────────────────────────────────────────────

app.get('/health', (_, res) => res.json({ status: 'ok', app: 'ecommerce-buyer', version: '1.0.0' }));

// ── Products ──────────────────────────────────────────────────────────────────

app.get('/api/products', (req, res) => {
  const { category, search, minPrice, maxPrice, sort, limit = 20, page = 1 } = req.query;

  let results = [...products];

  // Filter by category
  if (category) {
    results = results.filter(p => p.category === category);
  }

  // Search
  if (search) {
    const q = search.toLowerCase();
    results = results.filter(p =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q)
    );
  }

  // Price filter
  if (minPrice) results = results.filter(p => p.price >= parseInt(minPrice));
  if (maxPrice) results = results.filter(p => p.price <= parseInt(maxPrice));

  // Sort
  if (sort === 'price_low') results.sort((a, b) => a.price - b.price);
  if (sort === 'price_high') results.sort((a, b) => b.price - a.price);
  if (sort === 'rating') results.sort((a, b) => b.rating - a.rating);
  if (sort === 'newest') results.sort((a, b) => b.id.localeCompare(a.id));

  // Pagination
  const start = (parseInt(page) - 1) * parseInt(limit);
  const paginated = results.slice(start, start + parseInt(limit));

  res.json({
    success: true,
    data: paginated,
    pagination: {
      page: parseInt(page),
      limit: parseInt(limit),
      total: results.length,
      pages: Math.ceil(results.length / parseInt(limit))
    }
  });
});

app.get('/api/products/:id', (req, res) => {
  const product = products.find(p => p.id === req.params.id);
  if (!product) return res.status(404).json({ error: 'Product not found' });

  // Get reviews for this product
  const productReviews = reviews.get(req.params.id) || [];

  res.json({
    success: true,
    data: { ...product, reviewsList: productReviews }
  });
});

app.get('/api/products/featured', (_, res) => {
  const featured = products.filter(p => p.badges.includes('bestseller') || p.badges.includes('prime')).slice(0, 10);
  res.json({ success: true, data: featured });
});

app.get('/api/products/deals', (_, res) => {
  const deals = products.filter(p => p.badges.includes('deal') || p.originalPrice > p.price * 1.3);
  res.json({ success: true, data: deals });
});

app.get('/api/categories', (_, res) => {
  const categories = [...new Set(products.map(p => p.category))];
  const data = categories.map(cat => ({
    name: cat,
    count: products.filter(p => p.category === cat).length,
    image: products.find(p => p.category === cat)?.images?.[0]
  }));
  res.json({ success: true, data });
});

// ── Cart ───────────────────────────────────────────────────────────────────────

app.post('/api/cart/add', requireInternal, (req, res) => {
  const { userId, productId, quantity = 1 } = req.body;

  if (!userId || !productId) {
    return res.status(400).json({ error: 'userId and productId required' });
  }

  const product = products.find(p => p.id === productId);
  if (!product) return res.status(404).json({ error: 'Product not found' });

  if (!carts.has(userId)) {
    carts.set(userId, []);
  }

  const cart = carts.get(userId);
  const existing = cart.find(item => item.productId === productId);

  if (existing) {
    existing.quantity += quantity;
  } else {
    cart.push({ productId, quantity, price: product.price, name: product.name, image: product.images?.[0] });
  }

  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const items = cart.length;

  res.json({ success: true, cart, total, items });
});

app.get('/api/cart/:userId', (req, res) => {
  const cart = carts.get(req.params.userId) || [];
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);

  res.json({ success: true, cart, total, items: cart.length });
});

app.put('/api/cart/update', requireInternal, (req, res) => {
  const { userId, productId, quantity } = req.body;

  const cart = carts.get(userId);
  if (!cart) return res.status(404).json({ error: 'Cart not found' });

  const item = cart.find(i => i.productId === productId);
  if (!item) return res.status(404).json({ error: 'Item not found' });

  if (quantity <= 0) {
    const idx = cart.indexOf(item);
    cart.splice(idx, 1);
  } else {
    item.quantity = quantity;
  }

  const total = cart.reduce((sum, i) => sum + i.price * i.quantity, 0);

  res.json({ success: true, cart, total, items: cart.length });
});

app.delete('/api/cart/:userId/items/:productId', requireInternal, (req, res) => {
  const cart = carts.get(req.params.userId);
  if (!cart) return res.status(404).json({ error: 'Cart not found' });

  const idx = cart.findIndex(i => i.productId === req.params.productId);
  if (idx > -1) cart.splice(idx, 1);

  const total = cart.reduce((sum, i) => sum + i.price * i.quantity, 0);

  res.json({ success: true, cart, total, items: cart.length });
});

app.delete('/api/cart/:userId', requireInternal, (req, res) => {
  carts.set(req.params.userId, []);
  res.json({ success: true, cart: [], total: 0, items: 0 });
});

// ── Checkout & Orders ─────────────────────────────────────────────────────────

app.post('/api/checkout', requireInternal, (req, res) => {
  const { userId, address, paymentMethod } = req.body;

  const cart = carts.get(userId);
  if (!cart || cart.length === 0) {
    return res.status(400).json({ error: 'Cart is empty' });
  }

  const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const shipping = subtotal >= 499 ? 0 : 49;
  const discount = 0;
  const total = subtotal + shipping - discount;

  const order = {
    id: `ORD${Date.now()}`,
    userId,
    items: [...cart],
    subtotal,
    shipping,
    discount,
    total,
    address,
    paymentMethod,
    status: 'confirmed',
    paymentStatus: 'pending',
    trackingId: `TRK${Math.random().toString(36).substr(2, 8).toUpperCase()}`,
    estimatedDelivery: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString()
  };

  orders.set(order.id, order);
  carts.set(userId, []); // Clear cart

  res.status(201).json({ success: true, order });
});

app.post('/api/payment/verify', requireInternal, (req, res) => {
  const { orderId, transactionId } = req.body;

  const order = orders.get(orderId);
  if (!order) return res.status(404).json({ error: 'Order not found' });

  // Simulate payment verification
  order.paymentStatus = 'completed';
  order.status = 'processing';
  order.transactionId = transactionId || `TXN${Date.now()}`;

  orders.set(orderId, order);

  res.json({ success: true, order });
});

app.get('/api/orders/:userId', (req, res) => {
  const userOrders = Array.from(orders.values())
    .filter(o => o.userId === req.params.userId)
    .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));

  res.json({ success: true, orders: userOrders });
});

app.get('/api/orders/:userId/:orderId', (req, res) => {
  const order = orders.get(req.params.orderId);
  if (!order || order.userId !== req.params.userId) {
    return res.status(404).json({ error: 'Order not found' });
  }

  res.json({ success: true, order });
});

// ── Wishlist ───────────────────────────────────────────────────────────────────

app.post('/api/wishlist/add', requireInternal, (req, res) => {
  const { userId, productId } = req.body;

  if (!wishlists.has(userId)) {
    wishlists.set(userId, []);
  }

  const wishlist = wishlists.get(userId);
  if (!wishlist.includes(productId)) {
    wishlist.push(productId);
  }

  res.json({ success: true, wishlist });
});

app.get('/api/wishlist/:userId', (req, res) => {
  const wishlistIds = wishlists.get(req.params.userId) || [];
  const wishlistProducts = wishlistIds.map(id => products.find(p => p.id === id)).filter(Boolean);

  res.json({ success: true, wishlist: wishlistProducts });
});

app.delete('/api/wishlist/:userId/items/:productId', requireInternal, (req, res) => {
  const wishlist = wishlists.get(req.params.userId);
  if (!wishlist) return res.status(404).json({ error: 'Wishlist not found' });

  const idx = wishlist.indexOf(req.params.productId);
  if (idx > -1) wishlist.splice(idx, 1);

  res.json({ success: true, wishlist });
});

// ── Reviews ────────────────────────────────────────────────────────────────────

app.post('/api/reviews', requireInternal, (req, res) => {
  const { productId, userId, rating, title, comment } = req.body;

  const product = products.find(p => p.id === productId);
  if (!product) return res.status(404).json({ error: 'Product not found' });

  const review = {
    id: uuidv4(),
    productId,
    userId,
    rating,
    title,
    comment,
    helpful: 0,
    createdAt: new Date().toISOString()
  };

  if (!reviews.has(productId)) {
    reviews.set(productId, []);
  }
  reviews.get(productId).push(review);

  res.status(201).json({ success: true, review });
});

app.get('/api/reviews/:productId', (req, res) => {
  const productReviews = reviews.get(req.params.productId) || [];
  const avgRating = productReviews.length > 0
    ? productReviews.reduce((sum, r) => sum + r.rating, 0) / productReviews.length
    : 0;

  res.json({
    success: true,
    reviews: productReviews,
    summary: {
      average: avgRating.toFixed(1),
      count: productReviews.length
    }
  });
});

// ── Search ─────────────────────────────────────────────────────────────────────

app.get('/api/search', (req, res) => {
  const { q, suggestions } = req.query;

  if (!q) return res.json({ success: true, results: [], suggestions: [] });

  const results = products.filter(p =>
    p.name.toLowerCase().includes(q.toLowerCase()) ||
    p.description.toLowerCase().includes(q.toLowerCase()) ||
    p.category.toLowerCase().includes(q.toLowerCase())
  );

  const suggestions = [...new Set(results.map(p => p.name))].slice(0, 5);

  res.json({ success: true, results, suggestions, count: results.length });
});

// ── Recommendations ─────────────────────────────────────────────────────────────

app.get('/api/recommendations/:userId', (req, res) => {
  // Simple recommendation: trending + personalized
  const trending = products.filter(p => p.badges.includes('bestseller')).slice(0, 6);
  const deals = products.filter(p => p.badges.includes('deal')).slice(0, 4);

  res.json({
    success: true,
    recommendations: {
      trending,
      deals,
      recentlyViewed: []
    }
  });
});

app.listen(PORT, () => {
  console.log(`
╔══════════════════════════════════════════════════════════════╗
║  🛍️  E-Commerce Buyer App — PORT ${PORT}                        ║
║  AI-powered marketplace like Amazon/Flipkart              ║
╠══════════════════════════════════════════════════════════════╣
║  Products: ${products.length} items                                  ║
║  Categories: ${[...new Set(products.map(p => p.category))].length}                                                ║
╚══════════════════════════════════════════════════════════════╝
  `);
});

export default app;
